6213 Шестериков Б.В. Лаб.1 Вар.4
itsecd/isb pull request #10
Opened 2024-02-21 19:14 UTC by BarMan555

1. Шифровка текста с помощью шифра Цезаря со сдвигом +5. Результаты в папке first_task. Код реализации в first_task.py
2. Расшифровка текста методом частичного анализа. Результаты в папке second_task. Код реализации в second_task.py

work_with_file.py - функции для работы с файлами

2024-02-22 06:42 UTC, alxmcs requested changes
А остальные претензии будут от @Daria-creator-lab

2024-02-22 06:42 UTC, alxmcs commented on lab_1/second_task.py
> +    resultTxt = letter_dechiper(resultTxt, '\n', 'ы')
![image](https://github.com/itsecd/isb/assets/70561974/fcf3bab5-e8d7-467f-a879-577a67af09eb)

2024-02-22 06:42 UTC, alxmcs commented on lab_1/first_task.py
> +            i += 1
Алгоритмическая сложность этих манипуляций зашкаливает
Этот код можно и нужно оптимизировать

2024-02-22 11:33 UTC, Daria-creator-lab requested changes

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/first_task.py
> +from working_with_file import write_file, read_file, json_to_dict
не соответствует PEP

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +from working_with_file import json_to_dict, dict_to_json, read_file, write_file
не соответствует PEP

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +def dechiper(text : str, key : dict) -> str:
decipher, а лучше decryption

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +    return text
Ваша функция вызывает другую функцию, у которой только одна задача - replace
Так делать плохо. Перепишите.

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +    keyDict = dict(zip("МХ4У1rb<7cЕО>А2ДКЫФa5ЛtЬРП8ЙИБЧ\n", " налотгчйдсеиьпрюшмвбяущзжкхфэцы"))
Никаких захардкоженных значений/путей/магических чисел в коде быть не должно.

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/working_with_file.py
> +        logging.error(ex)
Добавить описание ошибки

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/working_with_file.py
> +    except Exception as ex:
Аналогично

2024-02-22 11:33 UTC, Daria-creator-lab commented on lab_1/working_with_file.py
> +        json.dump(dict, file)
А где обработка исключений?

2024-02-26 07:30 UTC, alxmcs approved these changes

2024-02-26 07:47 UTC, Daria-creator-lab requested changes

2024-02-26 07:47 UTC, Daria-creator-lab commented on lab_1/first_task.py
> +
Добавить описание ошибки
Проверить весь код

2024-02-26 07:47 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +NEW_SYMBOLS = " налотгчйдсеиьпрюшмвбяущз"
это огромная дыра в безопасности 
спрячьте в файл настройки

2024-02-26 07:47 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +                stats[letter] = count / length
зачем здесь if?

2024-02-26 08:16 UTC, BarMan555 commented on lab_1/second_task.py
> +                stats[letter] = count / length
Чтобы повторно не обрабатывать символы

2024-03-04 06:48 UTC, Daria-creator-lab approved these changes

2024-03-04 06:48 UTC, Daria-creator-lab commented on lab_1/second_task.py
> +                stats[letter] = count / length
Хорошо, что вы хотели оптимизировать свой код, но в данном случае код с проверкой отрабатывает медленнее, чем без нее

Время работы с if : 0:00:00.001741
Время работы: 0:00:00.001248

Можете провести эксперимент.

2024-03-04 06:50 UTC, BarMan555 commented on lab_1/second_task.py
> +                stats[letter] = count / length
Хорошо, понял =0

2024-04-04 13:05 UTC, closed without merging