6211 Пихуров М.А. Лаб.2 Вар.7
itsecd/isb pull request #100
Opened 2024-04-15 10:18 UTC by moter1026

Во 2-ой лабораторной работе сгенерировал псевдослучайные последовательности на языках C++ и Java. Произвёл тестирование данных последовательностей по методам NIST. 
Вывод написал в файле report.md

2024-04-15 12:38 UTC, ladyitsecurity requested changes

2024-04-15 12:38 UTC, ladyitsecurity commented on lab_2/cpp_prog/task_1/task_1.vcxproj
Ну что это такое.... убрать.

2024-04-15 12:38 UTC, ladyitsecurity commented on lab_2/cpp_prog/task_1/task_1.vcxproj.filters
Аналогично.

2024-04-15 12:38 UTC, ladyitsecurity commented on lab_2/tests.py
> +    """
Некорректно работает.

2024-04-15 12:38 UTC, ladyitsecurity commented on lab_2/tests.py
> +
Зачем?

2024-04-15 12:38 UTC, ladyitsecurity commented on lab_2/tests.py
> +                count = 0
Есть функция max()

2024-04-15 13:27 UTC, moter1026 commented on lab_2/cpp_prog/task_1/task_1.vcxproj
Я хотел убрать данные файлы, но без них не запустится SLN проект генерации случайной последовательности на языке C++. Я нигде не видел, чтобы было сказано, что SLN использовать нельзя.

Раз вас это настолько тронуло, что прям многоточие поставили, я уберу SLN проект и сделаю всё при помощи CMAKE

2024-04-15 13:35 UTC, moter1026 commented on lab_2/tests.py
> +
чтобы не происходило лишних проверок или действий. 
В данном случае мне нужно проверять на максимальное число подряд идущих единиц только после встречи символа 0. Когда такое происходит, то я перейду к следующему if-у. 
А если 1-ца была последней в последовательности, я после цикла проверяю какое значение больше (то, которое было или новое)

2024-04-15 13:52 UTC, moter1026 commented on lab_2/tests.py
> +                count = 0
исправил

2024-04-15 13:55 UTC, moter1026 commented on lab_2/tests.py
> +    """
Я проверил ещё раз момент с распределением по максимальным длинам последовательностей единиц. Там всё верно, насколько я увидел. В других местах не знаю где ещё может быть ошибка.

Если есть что-то конкретное, что вы имели в виду под  "некорректно работает", то напишите пожалуйста.

2024-04-17 06:06 UTC, ladyitsecurity commented on lab_2/tests.py
> +    """
Жизнь разработчиков - поиск багов. Было бы круто, если бы кто-то приходил и говорил, в какой именно строчке баг.

2024-04-17 06:27 UTC, ladyitsecurity requested changes

2024-04-17 06:27 UTC, ladyitsecurity commented on lab_2/tests.py
> +
Вы делаете двойную работу. Если вы продолжаете, то проверка ниже не нужна. Если вы проверяете ниже, то не нужен continue. Поэтому надо оставить что-то одно. Работать то будет без исправлений, но получается масло масляное и дополнительная проверка после смены флага все равно будет. И это тоже можно было бы понять в режиме дебага.

2024-04-21 15:33 UTC, ladyitsecurity approved these changes

2024-05-24 05:36 UTC, closed without merging