6211 Владимирцев А. Д. Лаб.1 Вар.3
itsecd/isb pull request #114
Opened 2024-04-21 17:33 UTC by Alex8608

2024-04-24 14:11 UTC, ladyitsecurity requested changes
Если у вас два мейна, то нужна декомпозиция (да и если один, в этой лабе тоже желательно) - двух папок будет достаточно.

2024-04-24 14:11 UTC, ladyitsecurity commented on lab_1/decrypting.py
> +    # json_writer(paths["key2"], key_dict)
Если есть что-то закомментированное, оно должно либо стать активным, либо удалено.

2024-04-24 14:58 UTC, Alex8608 commented on lab_1/encrypting.py
> +    :param keyword: str - keyword for encrypting:
Я использую шифр через таблицу Виженера, поэтому написал используя Vision Table

2024-04-25 13:28 UTC, ladyitsecurity approved these changes

2024-04-26 06:10 UTC, closed without merging