6211 Фролкин Н.С. Лаб.4 Вар.2
itsecd/isb pull request #115
Opened 2024-04-21 18:11 UTC by nick-vivo

[Asawcntratttsttthhtrtlmlsmycc] Номер варианта выбран, который дал преподаватель... Выводы в report.md и соотвествующей папки Solutions... Команды для ввода в файлах commands.txt, находящиеся в Solutions... Функция хеша была выбрана в соотвествии с вариантом blake2s................[fsg]

2024-05-19 19:19 UTC, nick-vivo commented
Коммиты были исправлены по требованию преподавателя, также была пофикшена конструкция if-else в основном приложении

2024-05-30 12:19 UTC, ladyitsecurity requested changes

2024-05-30 12:19 UTC, ladyitsecurity commented on lab_4/report.md
> +Не доверять свои личные данные сберу и хранить деньги в крипте.
Оформить результаты выполнения работы корректно.

2024-06-02 14:10 UTC, nick-vivo commented
Рапорт был изменён по приказу преподавателя.

2024-06-05 19:07 UTC, ladyitsecurity approved these changes

2024-07-21 23:43 UTC, closed without merging

2024-11-27 10:45 UTC, nick-vivo commented
происходит компрометация конф информации