6213 Журавлев С.А. Лаб.3 Вар.5
itsecd/isb pull request #117
Opened 2024-04-22 16:57 UTC by fl1n4

Реализовано приложение, которое будет выполняет три указанных ниже сценарии:

1) Генерация ключей гибридной системы
2) Шифрование данных гибридной системой
3) Дешифрование данных гибридной системой

2024-04-25 08:31 UTC, Daria-creator-lab commented
В description добавить название алгоритма шифрования

2024-04-25 08:50 UTC, Daria-creator-lab requested changes

2024-04-25 08:50 UTC, Daria-creator-lab commented on lab_3/main.py
> +
заменить на match/case

2024-04-25 08:50 UTC, Daria-creator-lab commented on lab_3/main.py
> +        decrypt_data(paths)
Вы вызываете функцию decrypt_data 
Эта функция реализована в этом модуле и в lab_3/task3/decrypt_data.py. 
Похоже на ненужную перегрузку функции. 

Вам точно нужно в этом модуле создавать 3 функции с названиями, как у методов из класса?

2024-04-25 08:50 UTC, Daria-creator-lab commented on lab_3/task2/encrypt_data.py
Странная декомпозиция кода. 
По сути у вас в одном модуле намешана и работа с файлами, и шифрование/дешифрование. 

Попробуй разделить не на модули для шифрования/дешифрования, а на модули 
- для работы с симметричной криптографией
- для работы с ассиметричной криптографией
- для вспомогательных операций - сериализации/десериализации ключей/текста
- импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании (это ваш мейн)

2024-05-02 18:50 UTC, fl1n4 commented
1.  Была произведена декомпозиция кода. Теперь код разделен на модули

- для работы с симметричной криптографией
- для работы с ассиметричной криптографией
- для вспомогательных операций
- main (импортирующий в себя предыдущие модули)


2. Конструкция if/elif была заменена на match/case

3. Убраны ненужные перегрузки функции

4. В описание была добавлено название алгоритма шифрования

2024-05-04 08:00 UTC, fl1n4 commented
@Daria-creator-lab

2024-05-07 05:48 UTC, Daria-creator-lab requested changes

2024-05-07 05:48 UTC, Daria-creator-lab commented on lab_3/AsymmCrypt.py
> +
количество пустых строк между функциями не соответствует PEP

2024-05-07 05:48 UTC, Daria-creator-lab commented on lab_3/SymmCrypt.py
> +            ciphertext = ciphertext[8:]
Никаких захардкоженных значений в коде быть не должно.
Записывайте вектор инициализации и шифротекст в разные файлы. Или сделайте словарь с ключами iv,  ciphertext.

2024-05-07 05:48 UTC, Daria-creator-lab commented on lab_3/SymmCrypt.py
> +                decrypted_text_file.write(plaintext)
у вас для этого есть функция

2024-05-07 05:48 UTC, Daria-creator-lab commented on lab_3/main.py
> +    parser.add_argument('-t', '--text_file', type=str, default='lab_3/texts/text.txt', help='Path to the text file (default: lab_3/texts/text.txt).')
используйте os.path.join для формирования пути

2024-05-07 05:48 UTC, Daria-creator-lab commented on lab_3/main.py
> +
дайте пользователю возможность зашифровать/расшифровать текст своими ключами

2024-05-10 17:09 UTC, fl1n4 commented on lab_3/main.py
> +
argparse и так предоставляет пользователю возможность зашифровать/расшифровать текст своими ключами

2024-05-13 09:50 UTC, Daria-creator-lab approved these changes

2024-05-17 05:26 UTC, closed without merging