6213 Ксеневич М.С Лаб.2 Вар.10
itsecd/isb pull request #120
Opened 2024-04-22 20:36 UTC by maeosha

В работе мы сгенерировали 2 псевдослучайные последовательности с помощью С++ и Java. Эти последовательности мы провели через три теста NIST для определения вероятности их случайности.

Код генерации на двух языках последовательностей находится в папке Generation
Реализация тестов выполнена на языке Python, код находится в файле tests.py
Полученные последовательности находятся по пути: stats/random_sequence.json
Полученные результаты тестов находятся по пути: stats/stats.txt

2024-04-25 09:08 UTC, Daria-creator-lab requested changes

2024-04-29 16:16 UTC, maeosha commented on lab_2/tests.py
> +        probabilities_pi: list = [[0, 0.2148], [0, 0.3672], [0, 0.2305], [0, 0.1875]]
этот массив играет роль и счетчика и держателя констант. [x][y], где x - количество подмассивов подходящих по условию, у - сама константа. с помощью такого массива очень удобно подставлять в формулу коэф. перед константой

2024-05-02 19:14 UTC, Daria-creator-lab requested changes

2024-05-02 19:14 UTC, Daria-creator-lab commented on lab_2/constants.py
Почему это файл .py? Он точно не является исполняемым. 
Если хотите сделать _файл с константами_ - это должен быть файл с настройками (json)
Если хотите _вынести переменные как константы_, то это можно делать в том же файле, где вы реализовываете тесты NIST (т.е там, где эти переменные используются)

2024-05-02 19:14 UTC, Daria-creator-lab commented on lab_2/file_work.py
> +        if os.path.exists(path_to_file):
?

2024-05-02 19:14 UTC, Daria-creator-lab commented on lab_2/main.py
> +                    default=os.path.join("stats/random_sequence.json"),
прочитайте еще раз, как пользоваться [os.path.join](https://docs.python.org/3/library/os.path.html#os.path.join)

2024-05-02 19:14 UTC, Daria-creator-lab commented on lab_2/tests.py
> +
количество пустых строк между функциями не соответствует PEP
исправить везде

2024-05-02 19:14 UTC, Daria-creator-lab commented on lab_2/tests.py
> +        probabilities_pi: list = [[0, PI_0], [0, PI_1], [0, PI_2], [0, PI_3]]
Это кривая реализация словаря , используйте сразу его 
https://docs.python.org/3/tutorial/datastructures.html

2024-05-02 19:14 UTC, Daria-creator-lab commented on lab_2/tests.py
> +        for i_index in range(0, len(sequence_value), 8):
это все еще не исправлено

2024-05-07 08:13 UTC, Daria-creator-lab requested changes

2024-05-07 08:13 UTC, Daria-creator-lab commented on lab_2/file_work.py
> +        logging.warning(f"The file {path_to_key_file} is not exist!", error)
Приведите обработку исключений к одному виду

2024-05-07 08:13 UTC, Daria-creator-lab commented on lab_2/tests.py
> +PI_3: float = 0.1875
Сделать из этого одну константу-список

2024-05-07 08:13 UTC, Daria-creator-lab commented on lab_2/tests.py
> +        for i_index in range(0, len(sequence_value), 8):
все еще не исправлено

2024-05-07 08:13 UTC, Daria-creator-lab commented on lab_2/tests.py
> +        probabilities_pi: dict = {PI_0: 0, PI_1: 0, PI_2: 0, PI_3: 0}
Разделите на две переменных. Список значений PI (вы его в константу вынесли) и словарь V_n 
Сейчас вы нарушаете SOLID

2024-05-07 08:13 UTC, Daria-creator-lab commented on lab_2/file_work.py
> +    :return sequence:
сделайте нормальное описание параметров

2024-05-15 05:47 UTC, Daria-creator-lab commented
Вы зачем повторное ревью запросили, если ничего не исправлено?

2024-05-15 08:05 UTC, maeosha commented
извините, я оказывается не запушил:(

2024-05-16 14:41 UTC, maeosha commented on lab_2/file_work.py
> +        logging.warning(f"The file {path_to_file} is not exist!", error)
я не понял вашу правку, поэтому и изменений практически не было сделано.

2024-05-17 08:01 UTC, closed without merging