6212 Агафонов А.А. Лаб.1 Вар.1
itsecd/isb pull request #123
Opened 2024-04-24 10:23 UTC by sk1fix

Представлены папки decoding и encoding

2024-04-24 13:49 UTC, ladyitsecurity requested changes
Написать в description каким способом шифровали. Проверить на орфографию все функции и названия файлов. Проверить на соответствие PEP. Везде прописать достринги.

2024-04-24 13:49 UTC, ladyitsecurity commented on lab_1/decoding/main.py
> +            print('No such file or directory')
1. Не использовать захардкоженные пути. Вынести все пути в отдельный файл. 
2. Использовать относительные пути. Если я захочу запустить этот код, мне надо будет создавать папку Ycheba?
3. Одна задача должна выполнять одну функцию. Если считаем частоты, то при чем тут работа с файлом? Декомпозировать.
4. Почитать про обработку исключений в питоне. Так делать, как вы, нельзя. 
5. Еще раз почитать про обработку исключений. Обработка исключений != условный оператор. Они отличаются типичностью поведения. Если вы в try и except выполняете почти одно и то же, то поведение типичное, и вы не кричите, что все пропало, а просто обрабатываете спокойно. Зачем тогда исключение, если ситуация типичная? 
6. Использовать f-strings.

Проще стереть и заново все написать.

2024-04-24 13:49 UTC, ladyitsecurity commented on lab_1/decoding/main.py
> +    return None
В питоне есть функция поиска по словарю. Не изобретайте велосипед и уберите это.

2024-04-24 13:49 UTC, ladyitsecurity commented on lab_1/decoding/main.py
> +           'ь': ',', 'ф': '.', 'ш': 'b', 'ц': '9', 'э': 'Ф', 'й': '?'}
Не соответствует PEP. Все константы выносим в отдельный файл. Если он есть в файле, то здесь его не дублируем, потому что:

1.  Дыра в безопасности, если мы храним везде этот ключ
2.  Дыра в безопасности, если мы храним в самом коде этот ключ
3.  Невозможность поменять пароль, если он прям в коде.
4.  Вероятность ошибок из-за версионности, если изменить ключ только в одном месте.

2024-04-24 13:49 UTC, ladyitsecurity commented on lab_1/decoding/main.py
> +
Аналогично комментариям выше. Применить их ко всему коду и проверить еще раз.

2024-04-24 13:49 UTC, ladyitsecurity commented on lab_1/decoding/main.py
> +    decoding('D:/Ycheba/isb/lab_1/decoding/code1.txt')
Не используем хардкод.

2024-04-24 13:49 UTC, ladyitsecurity commented on lab_1/encoding/main.py
> +           'Я': 'с', '0': '9', '1': '7', '2': '8', '3': '0', '4': '2', '5': '6', '6': '4', '7': '1', '8': '3', '9': '5'}
Аналогично.

2024-05-30 09:29 UTC, ladyitsecurity requested changes
Добавить гитигнор. Добавить в него папки пайкеш, который встречается в лабе 2 раза. Написать в дискашенс каким способом шифровали! Почитать про обработку исключений.

2024-05-30 09:29 UTC, ladyitsecurity commented on lab_1/functions.py
> +                key[i] = 0
Прочитать про обработку исключений. Обработка исключений != условному оператору. Если вы не выдираете вилку из розетки, а просто другое значение принимаете, то это не исключение, а _типичное поведение._

2024-05-30 13:52 UTC, sk1fix commented
Представлены папки encoding и decoding, в которых соответственно происходит зашифровка текста перестановками и расшифровка данного нам текста

2024-06-02 07:51 UTC, ladyitsecurity approved these changes

2024-06-02 07:51 UTC, ladyitsecurity commented on lab_1/functions.py
> +                temp += i
А еще в питоне есть функция replace()...

2024-06-06 13:17 UTC, closed without merging