6211 Котенков Григорий Станиславович Лаб.2 Вар.2
itsecd/isb pull request #128
Opened 2024-04-24 17:17 UTC by Grigory163

2024-05-06 08:13 UTC, ladyitsecurity requested changes
Написать в дискрипшн суть лабораторной. Именовать коммиты не датами, а сутью изменений.

2024-05-06 08:13 UTC, ladyitsecurity commented on lab_2/nist_tests.py
> +            logging.error(f"Error during the test execution: {ex}\n")
1 в 1 код Владимирцева. Кто у кого спер? 
![image](https://github.com/itsecd/isb/assets/91944899/a5f67bee-b817-4cb4-abbc-7c0331baf3b7)

2024-05-11 17:48 UTC, Grigory163 commented
В ходе лабораторной работы были сгенерированы псевдослучайные бинарные последовательности с помощью стандартных ГПСЧ языков Java и C++.
Были реализованы 3 теста линейки NIST и проверены с помощью сгенерированных последовательностей.
Результаты тестов записаны в отдельный файл. Написан отчет по выполненной работе.

2024-05-24 06:46 UTC, alxmcs approved these changes

2024-05-24 06:46 UTC, closed without merging