6214 Маслова А.Р. Лаб.3 Вар.7
itsecd/isb pull request #137
Opened 2024-04-29 14:44 UTC by maslova-alenka

В данной лабораторной работе была реализована гибридная криптосистема. Использованы два вида шифрования: асимметричный алгоритм RSA, симметричный алгоритм SM4. Взаимодействие с пользователем реализовано через argparse в main.py.Можно сгенерировать ключи, шифровать/дешифровать текст и симметричный ключ. В папке text предоставлены исходный, зашифрованный и расшифрованный тексты. В папке key- приватный, публичный, а также симметричный ключи.

2024-05-06 06:11 UTC, Daria-creator-lab requested changes

2024-05-06 06:11 UTC, Daria-creator-lab commented on lab_3/lab3-var7/asymmetric.py
> +        """
Разделите эту функцию на две: для сериализации публичного и приватного ключа

2024-05-06 06:11 UTC, Daria-creator-lab commented on lab_3/lab3-var7/main.py
> +    symmetric.encrypt(setting["initial_file"], setting["encrypted_file"])
В файле с настройками может не быть значения по ключу "symmetric_key", "initial_file", "encrypted_file" или вообще может не быть таких ключей.
Вне функции прочитайте файл с настройками и передавайте в  encryption_action сразу значения.

2024-05-06 06:11 UTC, Daria-creator-lab commented on lab_3/lab3-var7/main.py
> +    symmetric.decrypt(setting["encrypted_file"], setting["decrypted_file"])
аналогично

2024-05-06 06:11 UTC, Daria-creator-lab commented on lab_3/lab3-var7/main.py
> +    setting = read_json("setting.json")
Дайте пользователю возможность использовать свои ключи и свой текст 
Сейчас он этого не может

2024-05-06 06:11 UTC, Daria-creator-lab commented on lab_3/lab3-var7/symmetric.py
> +
количество пустых строк между функциями не соответствует PEP

2024-05-06 09:40 UTC, maslova-alenka commented on lab_3/lab3-var7/symmetric.py
> +
Можно уточнить? в замечании имеется в виду, что должно быть 2 пустые строки? просто это у меня методы класса, а между ними должна быть одна пустая строка...
PyCharm подчеркивает 2 пустые строки как нарушение PEP...
![tmIi3w2qJOg](https://github.com/itsecd/isb/assets/131409000/93d36a5f-6925-4366-b744-91c3b0c96a97)

2024-05-07 08:29 UTC, Daria-creator-lab approved these changes

2024-05-22 05:39 UTC, closed without merging