6213 Овсянников А.Н. Лаб. 2 Вар. 3
itsecd/isb pull request #141
Opened 2024-04-30 09:48 UTC by Prodigysy

В ходе лабораторной работы были сгенерированы псевдослучайные бинарные последовательности с помощью стандартных ГПСЧ языков C++ и Java 
Результаты работы генераторов хранятся в results.json
Были проведены тесты на случайность из набора NIST для проверки качества генераторов. Результаты тестов в result_of_tests.txt

2024-05-06 06:28 UTC, Daria-creator-lab commented on lab_2/report.md
> +    11011110010111011100100110100101100001110101100010011110011100011100100011111011011011111011000100011101111110101010100011101100
Можете посчитать вероятность совпадения двух случайных последовательностей длинной 128 бит?
Потому что ваши последовательности удивительным образом совпали с Сидорчук К.О

![image](https://github.com/itsecd/isb/assets/73466150/d9b6f87b-f19d-492c-87a2-3584e4f30c65)

2024-05-06 06:28 UTC, Daria-creator-lab commented
Вам выдается новое задание. Реализовать 3 любых теста NIST из списка (кроме тех, которые уже реализованы)

![image](https://github.com/itsecd/isb/assets/73466150/e926e284-75f0-4653-8c44-871482c1fb23)

Описание тестов вы можете найти в [документации](https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-22r1a.pdf)

2024-05-08 07:52 UTC, Prodigysy commented
@Daria-creator-lab

2024-05-09 09:11 UTC, Daria-creator-lab requested changes

2024-05-09 09:11 UTC, Daria-creator-lab commented on lab_2/results.json
> +    "java" : "11010100101011000100011101110010001000000111000101001000010010010010001101001000110000011110000010001011011101100000010000111100"
С какой вероятностью две случайные последовательности могут совпасть?

2024-05-09 09:11 UTC, Daria-creator-lab commented on lab_2/result_of_tests.txt
> +
Вас не смутило, что значения одинаковые?

2024-05-13 09:57 UTC, Daria-creator-lab requested changes

2024-05-13 09:57 UTC, Daria-creator-lab commented on lab_2/tests.py
> +
количество пустых строк между функциями не соответствует PEP

2024-05-13 12:30 UTC, Prodigysy commented
@Daria-creator-lab

2024-05-15 05:52 UTC, Daria-creator-lab approved these changes

2024-06-04 09:53 UTC, closed without merging