6213 Бейбулатов С.М. Лаб.1 Вар.3
itsecd/isb pull request #147
Opened 2024-05-01 14:24 UTC by leshiy2216

В первой части лабораторной работы мы шифровали текст, выбирая метод шифрования на свое усмотрение. У меня использовался шифр Цезаря. Во второй части задания нам необходимо расшифровать заданный текст, пользуясь методом частотного анализа. Ключом во второй части являются две переменные с алфавитом.

2024-05-06 07:37 UTC, Daria-creator-lab requested changes

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task1/key.txt
храните ключ в формате json

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +    f = open('unencrypted.txt', 'r', encoding='utf-8')
Никаких захардкоженных путей в коде быть не должно.

А что вам тут помешало использовать with open?

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +
Чтение и запись в файл вынести в отдельные функции

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +    normal_alphabet = " ОЕНЧЬГИТМСЛПЯВЭЙРКАЖЗДУ"
Никаких захардкоженных значений в коде быть не должно.
Все получать из файла с настройками

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +frequency()
сделайте нормальный мейн

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +def decrypt(text, decryption_mapping):
а где все докстринги?

2024-05-06 07:37 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +def frequency():
где файл с частотами? как вы получили ключ?

2024-05-09 09:32 UTC, Daria-creator-lab requested changes

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +        return f.read().upper()
добавить обработку исключений

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +        f.write(text)
добавить обработку исключений

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +        json.dump({'step': step}, f)
добавить обработку исключений

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +    the function read file
Все функции для работы с файлами вынести в отдельный модуль

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +    encrypt text using Caesar cipher.
Шифрование-обратимый процесс. Добавьте возможность расшифровать зашифрованное сообщение. 
Сделайте одну функцию, в которой режим шифрования/дешифрования выбирается через match/case.
Так вы сможете проверить правильность реализации вашего алгоритма.

*подсказка
для режима использовать структуру Enum

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/freq.py
> +                freq[char] = 1
Вы открыли файл на чтение и заполняете словарь freq. Зачем? 
Прочитали данные из файла -> обрабатываете их (не нужно это делать при открытом файле)

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/freq.py
> +
Это функции для работы с файлами, вынесите их в отдельный модуль

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/freq.py
> +            text_file.write(f"{char}: {frequency}\n")
сначала подготовьте данные (отсортируйте их), затем записывайте в файл

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/freq.py
> +    with open('cod3.txt', 'r', encoding='UTF-8') as f:
Никаких захардкоженных путей в коде быть не должно.

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/freq.py
> +    with open('cod3.txt', 'r', encoding='UTF-8') as f:
для чтения файла у вас есть функция, используйте ее

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +def frequency(input_file: str, output_file: str, settings_file: str, key_file: str) -> None:
функция с таким названием уже существует

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +from typing import Tuple
не соответствует PEP

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +
вынести в модуль для работы с файлами

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +
используйте функцию для чтения, которая уже у вас есть

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +        decrypted_file.write(decrypted_text)
используйте функцию для записи, которая уже у вас есть

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +        json.dump(decryption_mapping, key_file, ensure_ascii=False, indent=4)
вынести в отдельный модуль для работы с файлами 

Посмотрите, какие функции у вас будут в этом модуле. Они не должны нарушать SOLID

2024-05-09 09:32 UTC, Daria-creator-lab commented on lab_1/task2/result.txt
> +ДАЖЕ НЕСПЕчИАЛИСТУ ЯСНО ЧТО В ТОМ ЧИСЛЕ И ПО ЭТОЙ ПРИЧИНЕ РЛЕ НЕ ПРЕДСТАВЛЯЕТСЯ ОПТИМАЛЬНМ АЛГОРИТМОМ СЖАТИЯ? ПОСКОЛЬКУ ОН НЕ ИСПОЛЬЗУЕТ НИКАКОЙ ИНиОРМАчИИ О СЖИМАЕМОМ ТЕКСТЕ? ЧТОп ПОНЯТЬ КАК ПРОИСйО
текст расшифрован неверно

2024-05-13 10:02 UTC, ladyitsecurity commented
Запроса на ревью достаточно, упоминать в комментариях не нужно. Работу проверяет ваш преподаватель - Дарья Сергеевна, поэтому меня указывать не нужно.

2024-05-13 13:42 UTC, Daria-creator-lab requested changes

2024-05-15 06:07 UTC, Daria-creator-lab requested changes

2024-05-15 06:07 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +
Внутри функции объявить две новых функции это что-то очень странное 
Вы пробовали это скомпилировать? 

В прошлом ревью я написала вам 
_вместо if/else использовать [match/case](https://docs.python.org/3/tutorial/controlflow.html#match-statements)_

Используйте match/case !

2024-05-15 06:07 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +    }
У вас есть класс Mode, используйте его

2024-05-15 06:07 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +        print("Text decrypted successfully.")
вместо if/else использовать [match/case](https://docs.python.org/3/tutorial/controlflow.html#match-statements)

2024-05-15 06:07 UTC, Daria-creator-lab commented on lab_1/task2/freq.py
> +from task1.file_utils import save_to_json, save_to_text, read_file
не соответствует PEP

2024-05-15 06:07 UTC, Daria-creator-lab commented on lab_1/task2/frequency.py
> +    crypt_alphabet, normal_alphabet = read_settings(settings_file)
Читайте файл с настройками вне функции.

2024-05-16 22:51 UTC, leshiy2216 commented
исправил замечания, но не понимаю проблему в этом:
import argparse
from collections import Counter
from task1.file_utils import save_to_json, save_to_text, read_file

2024-05-22 06:01 UTC, Daria-creator-lab requested changes

2024-05-22 06:01 UTC, Daria-creator-lab commented on lab_1/task1/main.py
> +        print("Text decrypted successfully.")
Никаких захардкоженных путей в коде быть не должно
посмотрите, как вы сделали в другом модуле [lab_1/task2/frequency.py](https://github.com/itsecd/isb/pull/147/files#diff-3812c5c1ffdbc271258ea1c49391d4d88d4a577881dd4a3d2c6021a615552fa7)

2024-05-27 05:56 UTC, Daria-creator-lab approved these changes

2024-06-04 10:38 UTC, closed without merging