6211 Волков А.Ю. Лаб.2 Вар.4
itsecd/isb pull request #149
Opened 2024-05-01 15:17 UTC by VornadRkk

Во 2 лабораторной работе сгенерировал 2  псевдо случайные последовательности с помощью ГПСЧ и проверил насколько они случайны с помощью 3 тестов NIST.(Никак не могу удалить эти файлы, так как очень криво сделал коммит)

2024-05-06 08:24 UTC, ladyitsecurity requested changes
Написать в дискрипшн суть лабораторной. Почистить PR от файлов других лаб и не только.

2024-05-06 08:24 UTC, ladyitsecurity commented on lab_2/Test.py
> +from constants import BLOCK_SIZE,PATH,PI_VALUES
Не соответствует PEP. И название файла тоже не соответствует PEP.

2024-05-06 08:24 UTC, ladyitsecurity commented on lab_2/Test.py
> +
Это что такое? Импортируем в начале файла...

2024-05-08 16:51 UTC, ladyitsecurity requested changes
Удалить из пиара файлы других лаб и не только.

2024-05-12 15:52 UTC, ladyitsecurity requested changes
Убрать лишние файлы из пиара (другие лабы) и добавить в гитигнор этой лабы папки других лаб.

2024-05-14 16:05 UTC, ladyitsecurity requested changes

2024-05-14 16:05 UTC, ladyitsecurity commented on lab_2/Test.py
Имя файла не соответствует PEP.

2024-05-14 16:14 UTC, VornadRkk commented on lab_2/Test.py
какое название файла..

2024-05-16 13:58 UTC, ladyitsecurity commented on lab_2/Test.py
Сверху написано...

2024-05-17 07:03 UTC, closed without merging