6213 Шехматов Виктор Лаб.2 Вар.2
itsecd/isb pull request #153
Opened 2024-05-03 04:35 UTC by Nakamo312

2024-05-06 07:41 UTC, Daria-creator-lab commented
пустой description 👎

2024-05-06 07:42 UTC, Daria-creator-lab commented
Почистить файлы. lab1 здесь точно быть не должно 

![image](https://github.com/itsecd/isb/assets/73466150/429a55db-a0ad-4067-bcc9-4e62b2096400)

2024-05-07 08:20 UTC, Daria-creator-lab requested changes

2024-05-07 08:20 UTC, Daria-creator-lab commented on lab_2/data/java.json
> +  "LongestBitTest": 0.13183659,
неверные значения для тестов IdenticalBitTest, LongestBitTest

2024-05-07 08:20 UTC, Daria-creator-lab commented on lab_2/data/c++.json
> +  "LongestBitTest": 0.01644339,
неверные значения для тестов IdenticalBitTest, LongestBitTest

2024-05-07 08:25 UTC, Daria-creator-lab commented
В начале семестра старостам рассылались правила сдачи лабораторных работ по оиб.
Ознакомьтесь с ними еще раз. 

_1) прочитайте readme
2) язык программирования питон
2*) использовать Colab и jupiter notebook нельзя
3) можно сдавать не более 2 теорий за раз
4) введена бальная система:
за код можно получить до 2 баллов 
за теорию до 3 баллов
5) количество вопросов по теории зависит от вас (насколько вы хорошо отвечаете)
6) вопросы могут быть  по лабам, лекциям, коду и темам, связанным с ними (тер.вер и т.д)
7) для вопросов используйте https://github.com/itsecd/isb/discussions_

2024-05-18 21:03 UTC, Nakamo312 reviewed
'

2024-05-22 05:29 UTC, Nakamo312 commented
Я что то неверно делаю? Что у меня статусы 2 и 3 лабораторной не меняются, но вместе с этим я не вижу никаких комментариев или замечаний

2024-05-22 05:30 UTC, Nakamo312 commented
Я что то неверно делаю? Что у меня статусы 2 и 3 лабораторной не меняются, но вместе с этим я не вижу никаких комментариев или замечаний

2024-05-22 06:13 UTC, Daria-creator-lab requested changes

2024-05-24 08:46 UTC, alxmcs approved these changes

2024-05-24 08:49 UTC, closed without merging