6213 Ульянов Александр Вар.1
itsecd/isb pull request #154
Opened 2024-05-03 07:04 UTC by Sanechek600

2024-05-06 07:59 UTC, Daria-creator-lab requested changes

2024-05-06 07:59 UTC, Daria-creator-lab commented on lab_1/task1/encrypt.py
> +        json.dump(key, file, ensure_ascii=False)
вынести работу с файлами в отдельные функции

2024-05-06 07:59 UTC, Daria-creator-lab commented on lab_1/task1/encrypt.py
> +
количество пустых строк между функциями не соответствует PEP

2024-05-06 07:59 UTC, Daria-creator-lab commented on lab_1/task2/decrypt.py
а где функция для частотного анализа? 
как вы ключ получили?

2024-05-30 10:22 UTC, Sanechek600 commented on lab_1/task2/decrypt.py
Прикрепил .ipynb, с помощью которого был получен ключ

2024-05-30 16:35 UTC, Daria-creator-lab requested changes

2024-05-30 16:35 UTC, Daria-creator-lab commented on lab_1/cipher1.ipynb
сделайте из этого функции и исполняемый модуль .py
напоминаю, использовать Colab и jupiter notebook нельзя

2024-06-04 10:39 UTC, Daria-creator-lab approved these changes

2024-06-04 10:39 UTC, closed without merging