6212 Волков В.С. Лаб.3 Вар.5
itsecd/isb pull request #156
Opened 2024-05-03 13:32 UTC by comandir26

В рамках данной лабораторной работы я реализовал класс, представляющий собой гибридную криптосистему, в которой сообщение шифруется при помощи симметричного алгоритма, а ключ симметричного алгоритма - открытым ключом ассиметричного алгоритма. В качестве асимметричного алгоритма использовал RSA, а в качестве симметричного CAST5. Был предусмотрен пользовательный выбор длины ключа, как необязательный аргумент командной строки(значение по умолчанию: 8).
Генерация: python main.py settings.json -gen -key=8
Шифрование:python main.py settings.json -enc
Расшифровка: python main.py settings.json -dec

2024-05-08 15:39 UTC, ladyitsecurity requested changes

2024-05-08 15:39 UTC, ladyitsecurity commented on lab_3/main.py
> +        path_to_text = settings.get('source_text')
Изменить на match case. Предоставить возможность :

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам

2024-05-08 15:42 UTC, ladyitsecurity commented
Также произвести декомпозицию кода и обернуть в классы. Разделить на модули: 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

2024-05-09 19:16 UTC, comandir26 commented
В описании к парсеру написал, какие параметры нужно указывать в каждом режиме работы, если пользователь хочет сгенерировать ключи по своему пути, зашифровать и расшифровать свой текст. Итого 4 модуля, для работы с симметричной и ассиметричной криптографией, модуль для сериализации и десериализации, а также модуль main.

2024-05-10 08:25 UTC, ladyitsecurity approved these changes

2024-05-10 09:12 UTC, closed without merging