6214 Мантров И.А. Лаб.1 Вар.5
itsecd/isb pull request #16
Opened 2024-02-27 19:57 UTC by pafosz

В данной лабораторной работе демонстрируется работа шифрования методом Цезаря и методом простой подстановки (моноалфавитная замена). Все результаты выполнения работы записаны в папку [texts](https://github.com/pafosz/isb/tree/main/lab_1/texts).
(заранее каюсь, работал с веткой main, а не с той, что была предусмотрена)

2024-03-04 08:42 UTC, Daria-creator-lab requested changes

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/main.py
> +    if args.action == 'encrypt':
Заменить if/elif на match/case

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/main.py
> +# ОСТАВИТЬ!!!
этого не должно быть в открытом доступе 
все пути должны храниться в файле настройках

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/main.py
> +
Этого не должно быть здесь. Инструкция пишется в readme.md

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/main.py
> +    args = parser.parse_args()
Нарушен SOLID. 
Использование argparse вынести в main модуля. Эту функцию переименовать и оставить в ней реализацию работы с файлами. На вход функция принимает пути, по которым лежат файлы с текстом (зашифрованный текст, расшифрованный текст, ключ). Вызвать новую функцию в мейне модуля, с полученными из argparse параметрами.

*Подсказка
Путь указывать в add_argument

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/modules/additional_functions.py
> +            raise ValueError('I do not know such a language')
Использовать Enum

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/modules/additional_functions.py
> +            frequency[symbol] = 1 / lenght
Используйте функцию count вместо if-ов

2024-03-04 08:42 UTC, Daria-creator-lab commented on lab_1/modules/text_operations.py
> +    return text
Добавить обработку ошибок. 
Проверить весь код

2024-03-04 12:26 UTC, pafosz commented
Исправил недочёты, но не уверен насчёт исправления с argparse, я перенёс всё в другой модуль, но не понял по поводу функции и ее параметров. Если нынешний вариант не является верным, можете объяснить поподробнее?

2024-03-07 06:57 UTC, Daria-creator-lab requested changes

2024-03-07 06:57 UTC, Daria-creator-lab commented on lab_1/modules/decypher.py
> +    return decypher
Функция аналогична сaesar_cypher, отличие в одной строке 
Это нарушение SOLID

Сделайте одну функцию с возможностью выбора режима (шифрование или дешифрование), для режима используйте Enum

2024-03-07 06:57 UTC, Daria-creator-lab commented on lab_1/modules/my_parser.py
> +
1) Сделайте одну функцию для шифрования и дешифрования (комментарий в lab_1/modules/decypher.py). 
2) Напишите функцию, которая на вход принимает параметры: путь до файла, в который будет запись; путь до исходного файла, путь до файла с ключом, режим работы (шифрование или дешифрование); и вызывает функцию из пункта 1. В этой функции будет происходить вся работа с файлами, а так же шифрование или дешифрование

2024-03-07 06:57 UTC, Daria-creator-lab commented on lab_1/modules/my_parser.py
> +    args = parser.parse_args()
if \_\_name__ == "\_\_main__":
** вся работа с argparse**
вызов функции, которая описана в пункте 2

2024-03-07 06:57 UTC, Daria-creator-lab commented on lab_1/modules/cypher.py
> +
?

2024-03-10 11:36 UTC, pafosz commented on lab_1/modules/cypher.py
> +
Замечания учтены, ошибки исправлены

2024-03-11 09:57 UTC, Daria-creator-lab requested changes

2024-03-11 09:57 UTC, Daria-creator-lab commented on lab_1/modules/cypher.py
> +
Почему 0, 1? 

В классе Mode есть ENCRYPT и DECRYPT

2024-03-11 09:57 UTC, Daria-creator-lab commented on lab_1/main.py
> +
не соответствует PEP
проверить остальной код

2024-03-11 09:57 UTC, Daria-creator-lab commented on lab_1/modules/encryption_function.py
> +          print('you did not specify the action or the action does not exist')
1) разделить на две функции по заданиям: шифрование/дешифрование Цезарем, дешифрование с помощью частотного анализа 
2) не нужно писать одинаковые блоки кода - это нарушение SOLID
3) вы написали функцию сaesar_cypher, которая на вход принимает режим. Зачем здесь опять писать обработку для двух режимов? Передавайте в функцию режим - это сократит минимум 20 строк кода

2024-03-11 09:57 UTC, Daria-creator-lab commented on lab_1/modules/encryption_function.py
> +
Никаких  захардкоженных  путей

2024-03-11 09:57 UTC, Daria-creator-lab commented on lab_1/modules/additional_functions.py
> +            raise ValueError('I do not know such a language')
заменить на match/case

2024-03-14 08:26 UTC, Daria-creator-lab approved these changes

2024-03-14 08:26 UTC, Daria-creator-lab commented on lab_1/main.py
> +from modules.encryption_function import *
если импортируете все из модуля, можно просто заимпортировать модуль...

2024-04-04 13:06 UTC, closed without merging