6214 Круглов А.А. Лаб.2 Вар.2
itsecd/isb pull request #165
Opened 2024-05-06 09:16 UTC by AkatsukiDeki

В первом задании были сгенерированы псевдослучайные последовательности с помощью стандартных ГПСЧ языков С++ и Java. (на С/С++. 
Во втором - реализация трех тестов линейки NIST(частотный побитовый тест, тест на одинаковые подряд идущие биты и тест на самую длинную последовательность единиц в блоке  ) и проверка с их помощью сгенерированных последовательностей: NIST.py - тесты, results.txt - результаты.

2024-05-09 09:50 UTC, Daria-creator-lab requested changes

2024-05-09 09:50 UTC, Daria-creator-lab commented on lab_2/.idea/inspectionProfiles/Project_Default.xml
почистить файлы

2024-05-09 09:50 UTC, Daria-creator-lab commented on lab_2/GeneratorNumJava.java
> +        byte[] sequence = generateSecureRandomBytes();
В java есть [javadoc](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)
Аналогично для плюсов

2024-05-09 09:50 UTC, Daria-creator-lab commented on lab_2/read_write.py
> +        print("The file was not found")
добавить информацию об объекте исключения

2024-05-09 09:50 UTC, Daria-creator-lab commented on lab_2/read_write.py
> +        print(f"An error occurred while writing the file: {str(e)}")
Придерживайтесь одного стиля написания кода (см. read_json)

2024-05-16 11:16 UTC, AkatsukiDeki commented
@Daria-creator-lab проверьте пожалуйста

2024-05-16 11:19 UTC, Daria-creator-lab approved these changes

2024-05-22 05:45 UTC, closed without merging