6213 Ксеневич М. С. Лаб1 Вар10
itsecd/isb pull request #17
Opened 2024-03-03 09:44 UTC by maeosha

Шифровка, расшифровка простых методов шифрования

2024-03-04 09:41 UTC, Daria-creator-lab commented on lab_1/task2.py
> +    with open(os.path.join("decrypted_file.txt"), "w", encoding='utf-8') as file:
Никаких захардкоженных путей в коде быть не должно. 
В любую функцию путь должен передаваться как параметр.

2024-03-04 09:44 UTC, Daria-creator-lab commented on lab_1/decrypted_file.txt
> +Decrypted text:
где текст для 1 задания?

2024-03-04 09:46 UTC, Daria-creator-lab commented on lab_1/task1_main.py
> +                    default="abcdMaxim",
Никаких захардкоженных значений в коде быть не должно. Все данные получаем из файла

2024-03-04 09:48 UTC, Daria-creator-lab commented on lab_1/task1.py
> +        key_word[min_elem_index] = 1000
Никаких захардкоженных магических чисел в коде быть не должно.

2024-03-04 09:49 UTC, Daria-creator-lab commented on lab_1/task2.py
> +
А вы уверены, что нигде в вашем коде не возникнет исключение? 
Добавить обработку ошибок везде.

2024-03-04 09:50 UTC, Daria-creator-lab commented on lab_1/task2.py
> +    ave_stats: str = " оаинетслвпкурдябмьызюйгщэчжъфщхц"
Никаких захардкоженных значений в коде быть не должно.

2024-03-04 09:50 UTC, Daria-creator-lab commented on lab_1/task2.py
> +            stats[letter] = 1
используйте функцию count вместо if-ов

2024-03-04 09:52 UTC, Daria-creator-lab commented on lab_1/task2.py
> +
А как насчет [zip](https://docs.python.org/3.3/library/functions.html#zip)?

2024-03-13 07:13 UTC, Daria-creator-lab requested changes

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/task2.py
> +                key += line[0]
может все-таки [json.load()](https://docs.python.org/3/library/json.html)

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/task2.py
> +
А как насчет [zip](https://docs.python.org/3.3/library/functions.html#zip)?

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/task2.py
> +
Здесь точно нужно 2 цикла?

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/task2.py
> +        file.write(decrypted_text)
Где обработка исключений?

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/task2_main.py
> +
не соответствует PEP

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/task2_main.py
> +                    default='key_task2.txt',
Ключи хранить в json

2024-03-13 07:13 UTC, Daria-creator-lab commented on lab_1/text_task1
> +Всем прив я тут чилю и флексю вайб этого кода просто ваще блииин
Где зашифрованный файл?)

2024-04-08 06:49 UTC, Daria-creator-lab requested changes

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task1.json
> +  "text": "Всем прив я тут чилю и флексю вайб этого кода просто ваще блииин"
1) текст не должен лежать в одном файле с ключом 

2) прочитайте задание еще раз 
![image](https://github.com/itsecd/isb/assets/73466150/1f56632d-b36b-4563-81c5-6081f4add1c0)

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task1.py
> +    return info
сделайте декомпозицию кода 

все функции для работы с файлами вынести в отдельный модуль

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task1.py
> +    """Сreate a key from a keyword according to the alphabetical order of letters"""
сделайте нормальные докстринги с описанием параметров

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task1.py
> +
количество пустых строк между функциями не соответствует PEP
проверить везде

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task1.py
> +    except FileExistsError:
кроме ошибки из класса FileExistsError может быть и другая 
исправить везде

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task2.json
> +}
текст не должен лежать в одном файле с ключом

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task2.py
> +    return encrypted_text.replace("\n", "")
такая функция уже есть в [lab_1/task1.py](https://github.com/itsecd/isb/pull/17/files#diff-beb6a203754a84db50a9b4bd29d90134061732bc4f834d296c6778176521012b)

Нарушение SOLID

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task2.py
> +            key = [i[7] for i in json.load(file)["key"].split(", ")]
что за магическое число 7?

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task2.py
> +
изменять руками счетчик 👎
используйте [zip](https://docs.python.org/3.3/library/functions.html#zip)

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task2.py
> +        logging.warning(error, NameError)
такая функция уже есть в [lab_1/task1.py](https://github.com/itsecd/isb/pull/17/files#diff-beb6a203754a84db50a9b4bd29d90134061732bc4f834d296c6778176521012b)

Нарушение SOLID

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task1.py
> +def start_to_encrypt(path_to_file: str, path_to_decrypt: str) -> None:
тут решили вообще докстринги не делать?)

2024-04-08 06:49 UTC, Daria-creator-lab commented on lab_1/task2.py
> +def start_decrypt(path_to_file: str, path_to_decrypted_file: str) -> None:
докстринги....

2024-04-09 08:46 UTC, Daria-creator-lab requested changes

2024-04-09 08:46 UTC, Daria-creator-lab commented on lab_1/task2.py
> +            key = [i[7] for i in json.load(file)["key"].split(", ")]
Сейчас вы читаете файл с определенной позиции, если заменить файл, позиция чтения может измениться.

Вы можете либо передавать в функцию позицию, с которой нужно читать файл, либо (что будет правильнее) пересмотреть структуру файла.

2024-04-09 08:46 UTC, Daria-creator-lab commented on lab_1/task2.py
> +        logging.warning(error, NameError)
Вам нужно циклом пройтись по key и stats.keys(), положите их в zip. 

_for a, b in zip(key, stats.keys()):
        ..._

2024-04-18 06:54 UTC, Daria-creator-lab requested changes

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +    return encrypted_text.replace("\n", "")
нарушение SOLID
Эти функции выполняют чтение из json файла. В качестве параметра вы должны передавать только путь.
Путь до файла по ключу  должен быть получен вне функции

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +    return key
Это опять функция для чтения из json файла. Вы таких уже 2 написали выше

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +                file.write(str(text_dict))
Здесь тоже должен передаваться путь до файла. Обращение по ключу ["decrypted_text"] здесь быть не должно.

*Для хранения текста можно использовать .txt, не обязательно json

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +    except FileExistsError or FileNotFoundError as error:
Нельзя ловить два исключения сразу. Разделите их.
Кроме ошибки из класса FileExistsError и FileNotFoundError  может быть и другая
В конце ловите исключение общего вида

Почитайте про [исключения](https://docs.python.org/3/tutorial/errors.html)

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/task1.py
> +        key_word[min_elem_index] = tmp_big_elem
Реализуйте эту часть кода с помощью доступных методов для [списков и словарей](https://docs.python.org/3/tutorial/datastructures.html)

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/task1_main.py
> +
не соответствует PEP

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/task1_main.py
> +                    default="task1_key.json",
используйте os.path.join

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/task2.py
> +def get_stats(encrypted_text: str, key: list) -> str:
не соответствует PEP

2024-04-18 06:54 UTC, Daria-creator-lab commented on lab_1/task2_main.py
> +
!

2024-04-18 15:38 UTC, maeosha commented on lab_1/task1.py
> +        key_word[min_elem_index] = tmp_big_elem
а что не так с нынешней реализацией?

2024-04-25 05:59 UTC, Daria-creator-lab requested changes

2024-04-25 05:59 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +        logging.warning(f"The file {path_to_text_file} is not exist!", NameError)
Кроме ошибки из класса OSError может быть и другая
В конце ловите исключение общего вида

Исправить везде 

Почитайте про [исключения](https://docs.python.org/3/tutorial/errors.html)

2024-04-25 05:59 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +        if os.path.exists(os.path.join(path_to_decrypt)):
уберите конструкцию if/else вы ловите исключения в except

2024-04-25 05:59 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +
количество пустых строк между функциями не соответствует PEP
Исправить везде

2024-04-25 05:59 UTC, Daria-creator-lab commented on lab_1/task1_main.py
> +                    default="task1_key.json",
используйте os.path.join

если вы еще не работали с ним и/или не знаете, как с ним работать - это не повод игнорировать замечания 
почитайте [документацию](https://docs.python.org/3/library/os.path.html)

2024-04-25 05:59 UTC, Daria-creator-lab commented on lab_1/task2.py
> +    i = 0
i точно еще нужен?

2024-04-28 10:53 UTC, maeosha commented on lab_1/task2.py
> +    i = 0
Насчет замечания выше. Я использовал os.path.json посмотрите пожалуйста внимательно, в конце при вызове функции я передавал параметры через os.path.json

2024-04-28 10:54 UTC, maeosha commented on lab_1/file_work.py
> +        logging.warning(f"The file {path_to_text_file} is not exist!", NameError)
пожалуйста, напишите какая ошибка, я все обыскал. Я НЕ ПОНИМАЮ

2024-04-29 04:37 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +        logging.warning(f"The file {path_to_text_file} is not exist!", NameError)
Писала выше. В конце ловите исключение общего вида

Ваша обработка ошибок будет выглядеть следующим образом:
**try:**
**ваш код
**except OSError:**
**информация об ошибке
**except Exception as e:**
**информация об ошибке

2024-04-29 04:42 UTC, Daria-creator-lab commented
Исправьте все замечания, только после этого запрашивайте повторное ревью 

Пример неисправленных
![image](https://github.com/itsecd/isb/assets/73466150/828ea235-c189-438f-9579-862121d355b3)

2024-04-29 04:42 UTC, Daria-creator-lab commented on lab_1/task2.py
> +    i = 0
А зачем вы здесь пишете, если говорите о замечании выше?

2024-04-29 04:44 UTC, Daria-creator-lab commented on lab_1/task2.py
> +    i = 0
Хорошо, что вы в конце при вызове функции передаете параметры через os.path.json, но дефолтное значение тоже должно быть оформлено с помощью os.path.json

2024-04-29 04:46 UTC, Daria-creator-lab requested changes
Исправьте все замечания, только после этого запрашивайте повторное ревью 

Пример неисправленных
![image](https://github.com/itsecd/isb/assets/73466150/828ea235-c189-438f-9579-862121d355b3)

2024-05-02 18:58 UTC, Daria-creator-lab requested changes

2024-05-02 18:58 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +
количество пустых строк между функциями все еще не соответствует PEP

2024-05-02 18:58 UTC, Daria-creator-lab commented on lab_1/file_work.py
> +                file.write(str(text_dict))
_Здесь тоже должен передаваться путь до файла. Обращение по ключу ["decrypted_text"] здесь быть не должно._
это все еще не исправлено

2024-05-06 05:53 UTC, Daria-creator-lab approved these changes

2024-05-06 05:53 UTC, closed without merging