6212 Чуева Мария Олеговна Лаб.2 Вар.5
itsecd/isb pull request #174
Opened 2024-05-09 16:08 UTC by Lisyonok04

Был проведен статистический анализ на примере генераторов случайных чисел на языках C++ и Java с использованием NIST тестов
Результаты исследования приведены в файле results.md

2024-05-12 15:17 UTC, ladyitsecurity requested changes
Добавить _лабу1_ в гитигнор.

2024-05-12 15:17 UTC, ladyitsecurity commented on lab_2/NIST_test.py
> +                    sum += 1
Это можно написать в одну строчку и даже без if/else.

2024-05-12 15:17 UTC, ladyitsecurity commented on lab_2/results.md
Убрать #. Это же не питон файл, а md.

2024-05-12 15:45 UTC, Lisyonok04 commented on lab_2/results.md
Добрый вечер. Я прочитала документацию по оформлению md-файлов, где было написано, что различное количество "#" используется для различных уровней заголовков. 
В последовательностях и результатах тестов уберу, потому что это не заголовки, согласна. Но в остальном использовала "#" для красивого оформления) 
Заранее прошу прощения, если некорректно поняла ваше замечание

2024-05-13 07:53 UTC, ladyitsecurity approved these changes

2024-05-24 08:01 UTC, closed without merging