6212 Русяев А. Лаб.2 Вар.8
itsecd/isb pull request #179
Opened 2024-05-12 15:16 UTC by Amitroki

В данной лабораторной работе был проведен статистический анализ псевдослучайных последовательностей, которые были сгенерированы при помощи средств языков Java и C++. В папке _generators_ находятся файлы для генерации последовательностей, в папке _sequences_  выводы этих программ (сами последовательности), файл _functions.py_ содержит код для проведения тестов линейки NIST, а файл _nist.py_ проводит эти тесты для имеющихся последовательностей. 
Вывод о случайности данных последовательностей записан в файле _conclusion.txt_

2024-05-13 07:49 UTC, ladyitsecurity requested changes
[lab_1/sources/__pycache__] добавить в гитигнор, удалить из проекта на гите,

2024-05-13 07:49 UTC, ladyitsecurity commented on lab_2/constants.py
Не соответствует PEP.

2024-05-13 07:49 UTC, ladyitsecurity commented on lab_2/functions.py
> +    return gammainc(1.5, xi_distribution / 2)
Тест работает некорректно.

2024-05-13 12:09 UTC, Amitroki commented on lab_2/constants.py
Понял, сейчас сделаю с большой буквы название переменной

2024-05-13 12:14 UTC, Amitroki commented on lab_2/functions.py
> +    return gammainc(1.5, xi_distribution / 2)
Кажется я понял, где проблема - я некорректно считаю максимальное количество единиц в блоке, сейчас перепроверил это. Исправлю

2024-05-13 15:07 UTC, Amitroki commented
Внес коррективы в 3 тест (проблема была в подсчете подряд идущих единиц для конкретных случаев частей последовательности), вынес файл _.gitignore_ за пределы папки _lab_2_ с добавлением в него элементов, которые не должны присутствовать в этой лабораторной, написал константу с заглавной буквы по требованиям PEP

2024-05-14 15:49 UTC, ladyitsecurity approved these changes

2024-05-24 07:14 UTC, closed without merging