6211 Пихуров М.А. Лаб.3 Вар.8
itsecd/isb pull request #187
Opened 2024-05-14 20:02 UTC by moter1026

В данной лабораторной работе я реализовал гибридную криптосистему. 

При помощи библиотеки cryptography, используя симметричный алгоритм Blowfish (который не советуется использовать в практике) и асимметричный RSA. 

В процессе лабораторной работы:
* я сгенерировал ключи для симметричного и асимметричного алгоритмов. Зашифровал симметричный ключ при помощи ключа асимметричного алгоритма. Полученные ключи записал в необходимые файлы.
* зашифровал текст при помощи симметричного алгоритма
* расшифровал текст также при помощи симметричного алгоритма

2024-05-16 14:27 UTC, ladyitsecurity requested changes
Проверить на соответствие требованиям и исправить, если не соответствует: 

добавить возможность: 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам


Нужна дополнительная декомпозиция кода: разделение на несколько модулей: 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

2024-05-16 14:27 UTC, ladyitsecurity commented on lab_3/crypto.py
> +                                            encryption_algorithm=serialization.NoEncryption()))
Предоставить возможность обновить только один ключ: разделить на части.

2024-05-16 14:27 UTC, ladyitsecurity commented on lab_3/index.py
> +        print()
Заменить на match case.

2024-05-19 19:39 UTC, moter1026 commented on lab_3/index.py
> +        print()
в методичке написано через elif. А в дескрипшн написано, что это нужно для:
![image](https://github.com/itsecd/isb/assets/76918726/82a8ca39-4b41-41ac-9e2a-6be966468002)
 у меня здесь нет чисел или непонятных для понимания записей. Я не вижу разницы в том, что у меня будет написано ` if args.generation:` или `match param: 
 case Action.GENERATION`.
 
 Если есть принципиальная разница, то объясните пожалуйста.

2024-05-19 22:47 UTC, moter1026 commented
Добавил новые возможности для юзера по вашему уточнению выше. 

Не заменил только `else if` на `match case`, потому что непонятно для чего это нужно. Плюс в нынешней реализации мне необходимо использовать именно конструкцию `else if`, тк. я делаю доп проверку на введённые пользователем данные

2024-05-21 19:34 UTC, ladyitsecurity commented on lab_3/index.py
> +        print()
Можно ехать на велосипеде по колее. А можно пересесть во внедорожник. Если проверяется какое-то условие - используем if. А если у нас 4 разных варианта значений для одной переменной без длинных выражений для условия - это case. Это правила хорошего тона.

2024-05-24 06:32 UTC, alxmcs approved these changes

2024-05-24 06:38 UTC, closed without merging