6211 Зюзин Е.В. Лаб.3 Вар.8
itsecd/isb pull request #198
Opened 2024-05-19 12:18 UTC by derasoft004

Лабораторная работа 3
В лабораторной работе была реализована гибридная криптосистема. 
Использованы два вида шифрования: асимметричный алгоритм RSA, симметричный алгоритм Blowfish.
Интерфейс приложения реализован в виде интерфейса командной строки, поэтому запуск программы осуществляется только с использованием одного из параметров: -gen/-enc/-dec.
Для генерации ключа используется команда python3 main.py -gen (опционально можно добавить размер ключа, например: -len=64)
Для того, чтобы зашифровать исходное сообщение используется команда python3 main.py -enc
Для того, чтобы зашифровать исходное сообщение используется команда  python3 main.py -dec
В папке data предоставлены все .txt и .pem файлы для хранения данных о ключах и текстах.

2024-05-22 17:00 UTC, ladyitsecurity requested changes
Проверить заодно соответствие следующим требованиям: 

Должна быть возможность: 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам


Нужна дополнительная декомпозиция кода: разделение на несколько модулей: 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

2024-05-22 17:00 UTC, ladyitsecurity commented on lab_3/function_assistants.py
> +
А в предыдущем файле по отдельности обрабатывали исключения. Дискриминация. Привести с одному виду.

2024-05-22 17:00 UTC, ladyitsecurity commented on lab_3/.gitignore
Гитигнора много не бывает, да? Одного для достаточно.

2024-05-22 20:27 UTC, derasoft004 commented
> * сгенерировать ключи по своему пути,
> * зашифровать свой собственный текст с указанием путей к своим собственным ключам,
> * расшифровать свой собственный текст с указанием путей к своим собственным ключам

для генерации ключей по собственному пути используйте: python3 main.py -gen -public_key=data_test/public_key_test.pem -private_key=data_test/private_key_test.pem -sym_key=data_test/sym_key_test.pem 
для шифрования собственного текста с использованием собственных ключей используйте: python3 main.py -enc -text=data_test/text_test.txt -enc_path=data_test/enc_path_test.txt -public_key=data_test/public_key_test.pem -private_key=data_test/private_key_test.pem - sym_key=data_test/sym_key_test.pem
   для расшифровки собственного текста с использованием собственных ключей используйте: python3 main.py -dec -text=data_test/text_test.txt -dec_path=data_test/dec_path_test.txt -public_key=data_test/public_key_test.pem -private_key=data_test/private_key_test.pem - sym_key=data_test/sym_key_test.pem

2024-05-24 07:02 UTC, alxmcs approved these changes

2024-06-06 17:10 UTC, closed without merging