6211 Петров Григорий Лаб. 1 Вар. 8
itsecd/isb pull request #20
Opened 2024-03-03 20:23 UTC by gregory-237

Требовалось зашифровать фрагмент текста и записать результат шифрования и ключ в файл, также дешифровать текст с использованием алгоритма частотного анализа.

2024-03-06 08:16 UTC, alxmcs requested changes
Остальные претензии опишет @ladyitsecurity

2024-03-06 08:16 UTC, alxmcs commented on lab_1/task1/encrypt.py
> +    with open('files/input.txt', 'r', encoding='utf-8') as input_file:
Вынести захардкоженный путь в параметры функции

2024-03-06 08:16 UTC, alxmcs commented on lab_1/task1/encrypt.py
> +    with open('files/encrypt.txt', 'a', encoding='utf-8') as result_file:
Вынести захардкоженный путь в параметры функции

2024-03-06 08:16 UTC, alxmcs commented on lab_1/task1/encrypt.py
> +        result_file.write(f'KEYWORD: {keyword}')
По-моему, хранить зашифрованный текст и  ключ в одном и том же файле - не самая здоровая идея

2024-03-06 08:16 UTC, alxmcs commented on lab_1/task1/encrypt.py
> +    write_result(KEYWORD)
`KEYWORD` - параметр запуска софта, потенциальный пользователь твоего софта должен иметь возможность управлять им без необходимости редактировать исходники.
Так что передаваться он должен через настроечный файл или аргумент argparse

2024-03-06 08:16 UTC, alxmcs commented on lab_1/task2/decrypt.py
> +ENCRYPT_TEXT = f.readline()
![image](https://github.com/itsecd/isb/assets/70561974/260704f5-189c-4075-9010-0613027d7dff)

2024-03-06 08:16 UTC, alxmcs commented on lab_1/task2/decrypt.py
> +    with open('files/result.txt', 'a', encoding='utf-8') as f_result:
Захардкоженный путь вынести в параметры функции

2024-03-07 12:08 UTC, ladyitsecurity requested changes
Функцию def encryption(keyword: str, path: str) проще переписать заново с 0, все слишком нелогично. Обработку исключений поправить везде, подумать везде ли она уместна и в каких границах. Полностью убрать захардкоженные пути.

2024-03-07 12:08 UTC, ladyitsecurity commented on lab_1/task2/decrypt.py
> +        write_result('files/decrypt.txt', 'files/key.txt')
Пути не хардкодим, в отдельный какой-нибудь json выписываем (здесь и во всех подобных местах в коде)

2024-03-07 12:08 UTC, ladyitsecurity commented on lab_1/task2/decrypt.py
> +import logging
не соответствует PEP

2024-03-07 12:08 UTC, ladyitsecurity commented on lab_1/task2/decrypt.py
> +
Поправить обработку исключений.

2024-03-07 14:47 UTC, alxmcs approved these changes
Мои претензии удовлетворены, но мои претензии - не единственные к этому коду

2024-03-14 06:59 UTC, ladyitsecurity requested changes

2024-03-14 06:59 UTC, ladyitsecurity commented on lab_1/task1/encrypt.py
> +from constants import ALPHABET, PATHS
лишняя строка

2024-03-14 06:59 UTC, ladyitsecurity commented on lab_1/task2/decrypt.py
> +from constants import arr_encrypt_letters, PATHS
лишняя строка

2024-03-14 09:20 UTC, ladyitsecurity approved these changes

2024-04-12 06:35 UTC, closed without merging