6213 Овсянников А.Н. Лаб.3 Вар.4
itsecd/isb pull request #205
Opened 2024-05-20 10:34 UTC by Prodigysy

В ходе лабораторной работы была реализована гибридная криптосистема. В качестве асимметричного алгоритма используется RSA, симметричный алгоритм- 3Des 
В модуле crypto_system.py реализован класс Cryptography, который содержит методы для генерации ключей, шифрования и дешифрования текста.
В модуле write_read.py реализованы функции для работы с файловой системой.
В sym.py работа с симметричным ключом.
В модуле main.py было реализовано приложение на pyqt.

2024-05-22 13:34 UTC, Prodigysy commented
@Daria-creator-lab

2024-05-27 06:38 UTC, Daria-creator-lab requested changes

2024-05-27 06:38 UTC, Daria-creator-lab commented
Вы очень упорно пытаетесь меня обмануть уже 3 лабы подряд, крадя код других студентов. 

Ваше новое задание: 
- Гибридная криптосистема должна поддерживать несколько вариантов алгоритмов шифрования - [Camellia](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.Camellia), [Blowfish](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.Blowfish), [ChaCha20](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.ChaCha20) и ваш [3DES](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.TripleDES)
- Пользователю должна быть предоставлена возможность выбора алгоритма шифрования

2024-05-29 07:21 UTC, Daria-creator-lab requested changes

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +                f.write(public_key_pem)
работу с файлами вынести в отдельный модуль

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +                raise ValueError("Invalid encryption algorithm. Choose '3DES', 'Camellia', 'Blowfish', or 'ChaCha20'.")
использовать match/case

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +            if action == 'encrypt':
использовать match/case

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +                    data = data[16:]
Никаких захардкоженных значений в коде быть не должно.

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +        layout.addWidget(self.generate_keys_button)
дайте пользователю возможность зашифровать/расшифровать данные своими ключами

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +        self.sym_key_size_label = QLabel("Выберите размер симметричного ключа (бит):")
пользователь выбрал размер ключа 64 и алгоритм шифрования [ChaCha20](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.ChaCha20)

Как поведет себя ваша программа?

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +        else:
использовать match/case

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +            raise ValueError("Invalid symmetric key size. Choose 64, 128, 192, or 256 bits.")
данная функция неверна для алгоритма [Blowfish](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.Blowfish)

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
Сделайте декомпозицию кода. Сейчас в одном файле намешана работа с файлами, ассиметричной и симметричной криптографией.

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +        """Encrypts a file using hybrid encryption."""
Докстринги методов/функций должны включать в себя описание параметров

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +        """Decrypts a file using hybrid encryption."""
Докстринги методов/функций должны включать в себя описание параметров

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/crypto_system.py
> +    def _encrypt_decrypt(self, key, data, action):
а здесь вы устали докстринги писать?

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +class CryptoApp(QMainWindow):
где докстринги?

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +    def get_file_path(self, prompt):
докстринги

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +    def save_file_path(self, prompt):
докстринги

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +    def generate_keys(self):
докстринги

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +    def encrypt_text(self):
докстринги

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +    def decrypt_text(self):
докстринги

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/main.py
> +            return
пользователь должен иметь возможность использовать свои ключи

2024-05-29 07:21 UTC, Daria-creator-lab commented on lab_3/sym.py
> +def rsa_encrypt_decrypt(key, data, action):
докстринги

2024-05-30 09:26 UTC, Prodigysy commented
@Daria-creator-lab

2024-05-30 17:01 UTC, Daria-creator-lab requested changes

2024-05-30 17:01 UTC, Daria-creator-lab commented on lab_3/symmetric_crypto.py
> +                raise ValueError("Invalid symmetric key size. Choose 64, 128, 192, or 256 bits.")
с длиной ключа опять не угадали 
[Blowfish](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.algorithms.Blowfish), длина ключа от 32 до 448 бит с шагом 8 бит

Прочитайте методичку

2024-06-24 10:18 UTC, Daria-creator-lab approved these changes

2024-06-24 10:18 UTC, closed without merging