6213 Ксеневич М.С Лаб.4 Вар.10
itsecd/isb pull request #206
Opened 2024-05-20 18:49 UTC by maeosha

В этой лабораторной работе мы работали с банковскими картами. 
В 1ом пункте брудфорсом перебирается номер карты и сравнивается с хэшем. При этом для оптимизации перебора использовался мультипроцессинг.
Во 2ом пункте определяется корректность номера карты с помощью алгоритма Луна.
В 3ем пункте определяется время перебора номера карты с разным количеством процессов. Потом на основе этой статистики строится график.

2024-05-22 08:31 UTC, Daria-creator-lab requested changes

2024-05-22 08:31 UTC, Daria-creator-lab commented on lab_4/main.py
> +    default_card_number = "4377721789462148"
Никаких захардкоженных значений/путей в коде быть не должно. 
Храните их в файле с настройками

2024-05-29 07:25 UTC, Daria-creator-lab requested changes

2024-05-29 07:25 UTC, Daria-creator-lab commented on lab_4/config.json
> +    "card_bins": ["437772", "437783", "437773", "470127"],
Это все бины? Этого очень мало, найдите еще

2024-05-29 07:25 UTC, Daria-creator-lab commented on lab_4/file_work.py
> +
можно на это не проверять 
дальше у вас есть обработка исключений для файла

2024-05-29 18:52 UTC, maeosha commented on lab_4/config.json
> +    "card_bins": ["437772", "437783", "437773", "470127"],
больше нет бинов на визу тинькофф банка:( или мне можно их выдумать?

2024-05-30 17:03 UTC, Daria-creator-lab approved these changes

2024-06-04 09:52 UTC, closed without merging