6213 Шехматов Виктор Лаб3.Вар2
itsecd/isb pull request #208
Opened 2024-05-21 03:50 UTC by Nakamo312

. Реализовал класс HybridCryptosystem с использованием следующих алгоритмов:
     RSA для шифрования симметричного ключа
     Camellia для шифрования данных
2. Написал тесты для класса HybridCryptosystem, охватывающие различные сценарии использования и обработки ошибок.
3. Задокументировал класс и тесты с помощью docstrings для улучшения читаемости и понимания кода.

Результаты:

В результате проделанной работы был создан надежный и хорошо протестированный класс HybridCryptosystem, который можно использовать для  шифрования и дешифрования данных в различных приложениях.

2024-05-22 05:32 UTC, Nakamo312 reviewed
Я что то неверно делаю? Что у меня статусы 2 и 3 лабораторной не меняются, но вместе с этим я не вижу никаких комментариев или замечаний

2024-05-22 08:36 UTC, Daria-creator-lab requested changes

2024-05-22 08:36 UTC, Daria-creator-lab commented on lab_3/crypto.py
> +
не соответствует PEP

2024-05-22 08:36 UTC, Daria-creator-lab commented on lab_3/fetch_data.py
> +        logging.error(e)
добавьте описание ошибки

2024-05-22 08:36 UTC, Daria-creator-lab commented on lab_3/main.py
> +
дайте пользователю возможность 

- сгенерировать ключи по своему пути
- зашифровать свой собственный текст с указанием путей к своим собственным ключам
- расшифровать свой собственный текст с указанием путей к своим собственным ключам

2024-05-22 08:36 UTC, Daria-creator-lab commented on lab_3/main.py
> +        wr.write_txt(path["decrypted_file"],decrypt_text)
вместо if/elif используйте match/case

2024-09-23 07:48 UTC, Daria-creator-lab approved these changes

2024-09-23 07:49 UTC, closed without merging