6214 Кудашев Н.И. Лаб.1 Вар.3
itsecd/isb pull request #215
Opened 2024-05-22 16:47 UTC by thegr8nick

1.Зашифровка текста при помощи шифра Цезаря.
2.Дешифровка заданного текста методом частотного анализа.

2024-05-27 06:42 UTC, Daria-creator-lab requested changes

2024-05-27 06:42 UTC, Daria-creator-lab commented on lab_1/task2/text.txt
текст расшифрован неверно

2024-05-28 17:22 UTC, thegr8nick commented on lab_1/task2/text.txt
исправил

2024-05-30 17:05 UTC, Daria-creator-lab approved these changes

2024-06-04 10:43 UTC, closed without merging