6212 Зубков Д. О. Лаб.2 Вар.9
itsecd/isb pull request #217
Opened 2024-05-22 18:22 UTC by den3yb

Были получены две псевдослучайные последовательности битов с помощью генераторов на С++ и Java

Так же были проведены следующие статистические проверки случайности двоичных последовательностей методами NIST:
-Побитовый частотный тест
-Теста на одинаковые подряд идущие биты
-Теста на самую длинную последовательность единиц в блоке

На их основе был сформирован отчёт с выводом по проделанной работе

2024-05-30 10:08 UTC, ladyitsecurity requested changes

2024-05-30 10:08 UTC, ladyitsecurity commented on lab_2/tests/frequency_bit_test.py
> +            v[3] += 1
Заменить на match case

2024-05-30 10:08 UTC, ladyitsecurity commented on lab_2/tests/frequency_bit_test.py
> +            s += -1
В питоне есть функция count(). Если есть плюшки, то их надо использовать.

2024-06-02 08:15 UTC, ladyitsecurity approved these changes

2024-06-02 08:15 UTC, ladyitsecurity commented on lab_2/tests/frequency_bit_test.py
> +        )
Вынесите к занятию все это в разные функции. Никто не отменял разумную декомпозицию. Если вы их делите на блоки по обработке исключений, значит, есть смысл обособить в функции.

2024-06-03 07:58 UTC, den3yb commented on lab_2/tests/frequency_bit_test.py
> +        )
Извините за беспокойство, а если принты удалю(они нужны были для проверки, забыл убрать), то можно блоки не выносить в отдельные функции, ведь я просто вызываю тест сначала для с++ потом для джавы?

2024-06-06 10:41 UTC, closed without merging