6211 Котенков Григорий Станиславович Лаб.3 Вар.2
itsecd/isb pull request #219
Opened 2024-05-22 22:51 UTC by Grigory163

В данной лабораторной работе я реализовал класс, представляющий собой гибридную криптосистему, в которой сообщение шифруется при помощи симметричного алгоритма, а ключ симметричного алгоритма - открытым ключом ассиметричного алгоритма. В качестве асимметричного алгоритма использовался [RSA](http://www.michurin.net/computer-science/rsa.html), а в качестве симметричного ChaCha20. Был предусмотрен пользовательный выбор длины ключа, как необязательный аргумент командной строки(значение по умолчанию: 448).
Генерация ключа: python main.py settings.json -k=448
Шифрование:python main.py -enc
Расшифровка: python main.py -dec
Настроечный файл пользователя paths.json: python main.py -s

2024-05-30 11:08 UTC, ladyitsecurity requested changes
Проверить на соответствие следующим требованиям: 

Должна быть возможность: 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам


Нужна дополнительная декомпозиция кода: разделение на несколько модулей: 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

Пока не всему соответствует.

2024-05-30 14:03 UTC, Grigory163 commented
проверил, соответствует, всё есть в main файле)

2024-06-02 08:25 UTC, ladyitsecurity requested changes

2024-06-02 08:25 UTC, ladyitsecurity commented on lab_3/asymmetric_algorithm.py
> +            logging.error(f"Error in serializing public key - {e}")
Нужна дополнительная декомпозиция кода: разделение на несколько модулей:

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

Пока не соответствует.

Проверить еще раз)

2024-06-05 18:24 UTC, Grigory163 commented
> В данной лабораторной работе я реализовал класс, представляющий собой гибридную криптосистему, в которой сообщение шифруется при помощи симметричного алгоритма, а ключ симметричного алгоритма - открытым ключом ассиметричного алгоритма. В качестве асимметричного алгоритма использовался [RSA](http://www.michurin.net/computer-science/rsa.html), а в качестве симметричного Camellia. Был предусмотрен пользовательный выбор длины ключа, как необязательный аргумент командной строки(значение по умолчанию: 448). Генерация ключа: python main.py settings.json -k=448 Шифрование:python main.py -enc Расшифровка: python main.py -dec Настроечный файл пользователя paths.json: python main.py -s

2024-06-05 18:52 UTC, ladyitsecurity approved these changes

2024-06-07 06:56 UTC, closed without merging