6211-100503D Зюзин Е.В. Лаб.1 Вар.8
itsecd/isb pull request #22
Opened 2024-03-04 10:43 UTC by derasoft004

Во время выполнения лабораторной работы я изучил простейшие методы шифрования текстовых сообщений при помощи подстановки и перестановки, а также метода декодирования шифра простой замены на основе частотного анализа; получил навыки работы с шифрами.

Первое задание я выполнил с использованием шифра цезаря со сдвигом 16; 
Для второго задания потребовалось собрать статистику по символам в приведенном зашифрованном тексте и использовать ее для подбора ключа в соответствии с обычной частотой символов в русском языке. Основные трудности заключались в похожей частоте или одинаковом количестве употреблений в зашифрованном тексте некоторых символов.

2024-03-06 08:23 UTC, alxmcs requested changes
Остальные претензии будут от @ladyitsecurity

2024-03-06 08:23 UTC, alxmcs commented on .idea/.gitignore
Служебные

2024-03-06 08:23 UTC, alxmcs commented on .idea/inspectionProfiles/Project_Default.xml
Файлы

2024-03-06 08:23 UTC, alxmcs commented on .idea/inspectionProfiles/profiles_settings.xml
Среды

2024-03-06 08:23 UTC, alxmcs commented on .idea/isb.iml
Разработки

2024-03-06 08:23 UTC, alxmcs commented on .idea/misc.xml
Убрать

2024-03-06 08:23 UTC, alxmcs commented on .idea/modules.xml
Из

2024-03-06 08:23 UTC, alxmcs commented on .idea/vcs.xml
Репозитория

2024-03-06 08:23 UTC, alxmcs commented on lab_1/frequency_symbols_based.txt
Использовать вменяемый общепринятый формат сериализации

2024-03-06 08:23 UTC, alxmcs commented on lab_1/main.py
> +    frequency_lst = [i.replace('§', ' ') for i in read_file('frequency_symbols_based.txt').split('\n')]
Захардкоженный путь вынести в параметры функции

2024-03-06 08:23 UTC, alxmcs commented on lab_1/main.py
> +#
Это че

2024-03-06 08:23 UTC, alxmcs commented on lab_1/main.py
> +
Закомменченный код убрать из исходников

2024-03-06 08:23 UTC, alxmcs commented on lab_1/main.py
> +
Пустые строки убрать

2024-03-06 08:23 UTC, alxmcs commented on lab_1/requirements.txt
У тебя на машине одна единственная виртуальная среда на все проекты?
В этом файле должны быть только необходимые для запуска кода зависимости

2024-03-07 09:42 UTC, ladyitsecurity requested changes

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +"""
Это самое что?

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +RU_ALPH = 'АБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ'
Константы выносим в отдельный файл

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +        return ''.join(open(file_name, 'r').readlines())  # .replace('\n', '   ')
А закрыть файл?..

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +        return 'reading error:' + str(e)
Использовать эту связку внутри функции нельзя. Надо писать raise в функции и ловить вовне (а еще есть такая штука, как логирование)

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +        print(e)
Аналогично: не закрыт файл, исправить конструкцию.

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +        chr(ord(c) - 16) if c.isalpha() else c, string))
Добавить докстринг.

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +    write_file(file_to_write, rot16(read_file(file_to_read)))
Почему при чтении и записи выше концептуально могут быть ошибки, а тут нет?

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +    encrypted_text = read_file('task_2/cod8.txt')
Захардкоженные пути не используем, передаем их в качестве параметров, чтобы можно было поменять пути.

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +    encrypted_text = read_file('task_2/cod8.txt')
Аналогично путь передаем через параметры

2024-03-07 09:42 UTC, ladyitsecurity commented on lab_1/main.py
> +        key = json.load(f)
И еще раз, и во всех местах далее по коду...

2024-03-07 12:22 UTC, ladyitsecurity requested changes

2024-03-07 12:22 UTC, ladyitsecurity commented on lab_1/main.py
> +    task_2('task_2/cod8.txt', 'task_2/key.json', 'task_2/decipher_text.txt')
Остались захардкоженные пути.

2024-03-07 14:46 UTC, alxmcs approved these changes
Мои претензии удовлетворены, но мои претензии - не единственные к этому коду

2024-03-11 07:16 UTC, ladyitsecurity requested changes
Замечания не исправлены. 
![image](https://github.com/itsecd/isb/assets/91944899/dd8168a5-1b95-4b93-94f6-c238e98ff082)

2024-03-14 06:57 UTC, ladyitsecurity requested changes
Вы уверены, что нет случаев, когда что-то упадет? Добавьте обработку исключений.

2024-03-25 12:40 UTC, ladyitsecurity requested changes

2024-03-25 12:40 UTC, ladyitsecurity commented on lab_1/main.py
> +            ret_str += symbol
Это типичное поведение, не нужно использовать исключения и потом делать вид, что все ок, если вы знаете, что там есть лишние символы. Для этого можно использовать if и else, например...

2024-03-25 12:40 UTC, ladyitsecurity commented on lab_1/main.py
> +    :return:
Докстринги не дописаны. Везде.

2024-03-28 12:41 UTC, ladyitsecurity approved these changes

2024-04-12 06:33 UTC, closed without merging