6213 Козловская К. А. Лаб. 3 Вар. 8
itsecd/isb pull request #224
Opened 2024-05-25 13:55 UTC by Pomi44

Реализовано приложение, которое выполняет три указанных ниже сценария:

Генерация ключей гибридной системы
Шифрование данных гибридной системой
Дешифрование данных гибридной системой
Алгоритм шифрования: Blowfish, длина ключа 128 бит

2024-05-27 07:19 UTC, Daria-creator-lab requested changes

2024-05-27 07:19 UTC, Daria-creator-lab commented on lab_1/task_1/config1.json
файлов из 1 и 2 лабы здесь быть не должно

2024-05-27 07:19 UTC, Daria-creator-lab commented on lab_3/__pycache__/asymm_crypto.cpython-311.pyc
это тоже все почистить

2024-05-27 07:19 UTC, Daria-creator-lab commented on lab_3/main.py
> +        config = json.load(f)
обработка исключений

2024-05-27 07:19 UTC, Daria-creator-lab commented on lab_3/main.py
> +            private_key, public_key = asymm_crypt.generate_key_pair()
дайте пользователю 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам

2024-05-27 11:38 UTC, Pomi44 commented on lab_3/main.py
> +            private_key, public_key = asymm_crypt.generate_key_pair()
я даю пользователю возможность либо изменить операцию  которую код будет выполнять, либо самостоятельно загрузить путь к файлу config, где он сможет указать все нужные ему путь сразу

2024-05-29 07:38 UTC, Daria-creator-lab approved these changes

2024-05-31 04:45 UTC, closed without merging