6213 Сидорчук К.О. Лаб. 3 Вар. 6
itsecd/isb pull request #225
Opened 2024-05-25 18:04 UTC by Defoult13

Реализована программа, выполняющая указанные ниже сценарии:
алгоритм шифрования - SEED, длина ключа - 128 бит

Генерация ключей гибридной системы
Шифрование данных гибридной системой
Дешифрование данных гибридной системой

2024-05-27 07:23 UTC, Daria-creator-lab requested changes

2024-05-27 07:23 UTC, Daria-creator-lab commented on lab_3/main.py
> +        config = json.load(file)
обработка исключений

2024-05-27 07:23 UTC, Daria-creator-lab commented on lab_3/main.py
> +            private_key, public_key = asymm_crypt.generate_key_pair()
дайте пользователю 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам

2024-05-27 07:32 UTC, Defoult13 commented on lab_3/main.py
> +            private_key, public_key = asymm_crypt.generate_key_pair()
Пользователь может указать путь к своему json файлу с нужными ему путями

2024-05-29 07:39 UTC, Daria-creator-lab approved these changes

2024-05-31 05:53 UTC, closed without merging