6212 Клюшин И.С. Лаб. 2 Вар. 1
itsecd/isb pull request #228
Opened 2024-05-26 12:13 UTC by LoKe112

Были сгенерированы последовательности на C++ и Java при помощи ГСПЧ. Были проведены NIST тесты для того чтобы убедиться в качестве сгенерированных последовательностей

2024-05-30 10:49 UTC, ladyitsecurity requested changes

2024-05-30 10:49 UTC, ladyitsecurity commented on lab_2/nist.py
> +            )
Ужать до пары строк. Что за дискриминация между 47 строкой и 48-55..

2024-05-30 10:49 UTC, ladyitsecurity commented on lab_2/result.txt
Результаты тестов для одной их последовательностей указаны неверно.

2024-05-30 18:24 UTC, LoKe112 commented on lab_2/result.txt
Хотел бы уточнить что под этим подразумевается, при повторном запуске на моем ПК программа выдала те же результаты, что и в Result, или дело в том что ошибка заключается в одном из nist тестов или самой последовательности?

2024-06-02 08:11 UTC, ladyitsecurity approved these changes

2024-06-06 12:37 UTC, closed without merging