6213 Акутин И.Д. Лаб.1 Вар.1
itsecd/isb pull request #24
Opened 2024-03-08 13:50 UTC by Darktezi

Текста для первого задания находятся в папке [task1](https://github.com/Darktezi/isb/tree/lab1-var1/lab_1/task1).
Код для выполнения первого задания - [cipher.py](https://github.com/Darktezi/isb/blob/lab1-var1/lab_1/cipher.py).

Текста для второго задания находятся в папке [task2](https://github.com/Darktezi/isb/tree/lab1-var1/lab_1/task2).
Код для выполнения второго задания - [decrypter.py](https://github.com/Darktezi/isb/blob/lab1-var1/lab_1/decrypter.py).

2024-03-11 10:43 UTC, Daria-creator-lab requested changes

2024-03-11 10:43 UTC, Daria-creator-lab commented on lab_1/cipher.py
> +from writer_and_reader import read_from_file, write_to_file
не соответствует PEP

2024-03-11 10:43 UTC, Daria-creator-lab commented on lab_1/cipher.py
> +    """
В первом задании необходимо зашифровать и расшифровать текст алгоритмом шифрования Цезаря.

2024-03-11 12:54 UTC, Darktezi commented on lab_1/cipher.py
> +    """
расшифрововать текст нужно во втором задании, в первом только зашифровка 
![Screenshot 2024-03-11 165152](https://github.com/itsecd/isb/assets/125239326/e0ae39be-67d1-4460-a79a-a491b9404325)

2024-03-14 07:28 UTC, Daria-creator-lab requested changes

2024-03-14 07:28 UTC, Daria-creator-lab commented on lab_1/cipher.py
> +    """
Шифрование - обратимое преобразование, т.е. предусматривает обратную функцию. 

Ваша функция только шифрует сообщение. Для проверки корректности вашего алгоритма необходима функция, которая дешифрует зашифрованное сообщение.

2024-03-16 16:50 UTC, Daria-creator-lab requested changes

2024-03-16 16:50 UTC, Daria-creator-lab commented on lab_1/cipher.py
> +        logging.error(f"Can't decrypt text: {ex}\n")
Эта функция копия caesar_encrypt с отличием в одной строке. Это нарушение SOLID

Попробуйте передавать в функцию режим (шифрование или дешифрование), тогда у вас будет одна функция для алгоритма Цезаря.
* подсказка. Используйте Enum для режима

2024-03-16 16:50 UTC, Daria-creator-lab commented on lab_1/writer_and_reader.py
> +        logging.error(f"Error while writing to file'{filename}'.")
Здесь стоит добавить еще один except для исключений, не попавших в класс IOError.

2024-03-17 08:21 UTC, Daria-creator-lab requested changes

2024-03-17 08:21 UTC, Daria-creator-lab commented on lab_1/cipher.py
> +                result_text += rus_alphabet[new_position]
вместо if/else использовать match/case

2024-03-17 08:21 UTC, Daria-creator-lab commented on lab_1/cipher.py
> +
и поправьте везде число пустых строк, чтобы соответствовало PEP

2024-03-18 06:41 UTC, Daria-creator-lab approved these changes

2024-04-19 05:36 UTC, closed without merging