6211 Алехин И.И. Лаб.3 Вар.1
itsecd/isb pull request #241
Opened 2024-05-28 23:24 UTC by IvanAlehin

В данной лабораторной работе я реализовал класс, представляющий собой гибридную криптосистему, в которой сообщение шифруется при помощи симметричного алгоритма, а ключ симметричного алгоритма - открытым ключом ассиметричного алгоритма. В качестве асимметричного алгоритма использовался RSA, а в качестве симметричного AES. Был предусмотрен пользовательный выбор длины ключа, как необязательный аргумент командной строки(значение по умолчанию: 128).
Генерация ключей: python main.py -gen_key 
Шифрование:python main.py -enc
Дешифрование: python main.py -dec

2024-05-30 11:22 UTC, ladyitsecurity requested changes
Проверить на соответствие следующим требованиям: 

Должна быть возможность: 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам


Нужна дополнительная декомпозиция кода: разделение на несколько модулей: 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

Пока не всему соответствует.

2024-05-30 11:22 UTC, ladyitsecurity commented on lab_3/file_work.py
> +
Дописать докстринги для класса.

2024-05-31 21:13 UTC, IvanAlehin commented
Возможность :
- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам
есть в файле [main.py](https://github.com/IvanAlehin/isb/blob/lab3-var1/lab_3/main.py)

Дополнительная декомпозиция кода: разделение на несколько модулей:

- модуль для работы с симметричной криптографией [symmetric_algorithm.py](https://github.com/IvanAlehin/isb/blob/lab3-var1/lab_3/symmetric_algorithm.py)
- модуль для работы с ассиметричной криптографией [asymmetric_algorithm.py](https://github.com/IvanAlehin/isb/blob/lab3-var1/lab_3/asymmetric_algorithm.py)
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста [file_work.py](https://github.com/IvanAlehin/isb/blob/lab3-var1/lab_3/file_work.py)
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании [hybrid_system.py](https://github.com/IvanAlehin/isb/blob/lab3-var1/lab_3/hybrid_system.py)

2024-06-02 08:30 UTC, ladyitsecurity approved these changes

2024-06-06 08:59 UTC, closed without merging