6212 Дьячков К.А. Лаб.3 Вар.6
itsecd/isb pull request #244
Opened 2024-05-29 18:17 UTC by feelpainagain

Реализована гибридная криптосистема, в которой сообщение шифруется при помощи симметричного алгоритма SEED, ключи же шифруются при помощи асимметричного алгоритма RSA.

2024-05-30 11:25 UTC, ladyitsecurity requested changes
Проверить на соответствие следующим требованиям: 

Должна быть возможность: 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам


Нужна дополнительная декомпозиция кода: разделение на несколько модулей (каждый модуль - свой класс и файл): 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

Пока не соответствует.

2024-05-30 11:25 UTC, ladyitsecurity commented on lab_3/crypt_asymmetric.py
> +from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
Не соответствует PEP.

2024-06-05 18:50 UTC, ladyitsecurity requested changes
Прочитать еще раз предыдущие замечания. И исправить.

2024-06-05 18:50 UTC, ladyitsecurity commented on lab_3/functions.py
Гляжу в книгу....

2024-06-05 18:50 UTC, ladyitsecurity commented on lab_3/keys_functions.py
Вижу фигу...

2024-06-05 18:50 UTC, ladyitsecurity commented on lab_3/work_files.py
Везде....

2024-06-05 19:09 UTC, feelpainagain commented on lab_3/work_files.py
Довольно исчерпывающие и содержательные замечания по лабораторной работе.
Однако, я всё ещё не понимаю, каким условиям не соответствует моя лабораторная работа. Пожалуйста, укажите конкретные фрагменты кода, которые условиям не удовлетворяют.

2024-06-05 20:19 UTC, ladyitsecurity commented on lab_3/work_files.py
Вот этим:

> Нужна дополнительная декомпозиция кода: разделение на несколько модулей (каждый модуль - свой **_класс_** и файл)

Читаем требования внимательно.

2024-06-06 12:24 UTC, ladyitsecurity approved these changes

2024-06-07 08:27 UTC, closed without merging