6213 Яковлева Я.А. Лаб.2 Вар.6
itsecd/isb pull request #25
Opened 2024-03-10 21:28 UTC by dou1eur

В процессе работы были написаны 2 ГСПЧ с помощью генераторов на языках программирования C++ и Java, а также проведены тесты NIST для псевдослучайных последовательностей

2024-03-11 11:07 UTC, Daria-creator-lab requested changes

2024-03-11 11:07 UTC, Daria-creator-lab commented on lab_2/nist.py
> +                        statistics["v4"] += 1
Посмотрите, что у вас получается в statistics.
Для последовательности C++ есть блок 00010100, в нем максимальное число подряд идущих единиц =1

2024-03-13 16:38 UTC, dou1eur commented on lab_1/chipher.py
> +import logging
![l](https://github.com/itsecd/isb/assets/136986433/1d0ccfff-0236-4d72-8fb6-b464ed8fac2f)
Я закоммитила данный файл в ветке 1 лабораторной (потому что были даны еще комментарии), но зафиксировала лишь локально и создала новую ветку. Попробовала перенести коммит через git cherry-pick, но не получилось(

2024-03-14 07:39 UTC, Daria-creator-lab requested changes

2024-03-14 07:39 UTC, Daria-creator-lab commented on lab_2/nist.py
> +    try:
Исправить обработку исключений

* https://docs.python.org/3/tutorial/errors.html

2024-03-14 07:39 UTC, Daria-creator-lab commented on lab_2/nist.py
> +        settings = json.load(json_f)
Здесь тоже лучше добавить обработку исключений

2024-03-29 06:38 UTC, Daria-creator-lab approved these changes

2024-05-03 05:35 UTC, closed without merging