6214 Жирнов Владислав Евгеньевич Лаб.1 Вар.9
itsecd/isb pull request #26
Opened 2024-03-12 13:32 UTC by VladZhirnov

Научился шифровать текст методом Цезаря, т. е. методом простой подстановки. А также дешифровать текст с помощью метода частотного анализа.

2024-03-14 07:56 UTC, Daria-creator-lab requested changes

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ"
вынести в файл настройки или хотя бы в константу

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +        templates = json.load(f)
Никаких захардкоженных путей в коде быть не должно. Все они должны быть вынесены  в настройки приложения.

Путь до файла передавать в функцию в качестве аргумента.

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +        original = file.read().upper()
аналогично

проверить весь код

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +    print(original)
Копия функции encryption_by_substitution() с отличием в одной строке. Так делать не надо. Это нарушение SOLID. 

Сделайте одну функцию,  в которую в качестве параметра будет передаваться режим(шифрование или дешифрование). 

*подсказка 
используйте match/case для выбора режима

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +    count = len(original) - 10
Почему минус 10?
Никаких магических чисел в коде быть не должно

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +        encoded_text = file.read().upper()
добавить обработку исключений

2024-03-14 07:56 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +
Никаких захардкоженных путей в коде быть не должно. Все они должны быть вынесены в настройки приложения.

2024-03-16 17:03 UTC, Daria-creator-lab requested changes

2024-03-16 17:03 UTC, Daria-creator-lab commented on lab_1/result1.txt
> +DQQMU ECP KPURKTG WU VQ ITGCV VJKPIU, IKXG WU PGY KFGCU CPF RGTURGEVKXGU. OGGVKPI YKVJ C YQTM QH IGPKWU ECP DG CP KORGVWU VQ AQWT QYP ETGCVKXKVA, JGNR AQW HKPF CP KPGZJCWUVKDNG UVTGCO QH KPURKTCVKQP.
Не хватает файла с расшифрованным текстом для первого задания.

2024-03-17 08:51 UTC, VladZhirnov commented
Расшифрованный текст находится в файле original1.txt

2024-03-18 06:47 UTC, Daria-creator-lab requested changes

2024-03-18 06:47 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +    print(output)
Исправить обработку исключений, проверить весь код

https://docs.python.org/3/tutorial/errors.html


*подсказка
try:
   //**код**
except

2024-03-18 06:47 UTC, Daria-creator-lab commented on lab_1/lab1.py
> +
и поправьте везде число пустых строк, чтобы соответствовало PEP

2024-03-18 06:50 UTC, Daria-creator-lab commented
> Расшифрованный текст находится в файле original1.txt

Это исходный текст. В итоге у вас должно получиться 3 файла: исходный текст, зашифрованный и расшифрованный, чтобы вы могли сравнить исходный текст и расшифрованный и проверить корректность работы вашего алгоритма.

2024-03-18 08:13 UTC, VladZhirnov commented
Расшифрованный текст теперь находится в файле decrypted_text1.txt

2024-03-19 13:57 UTC, Daria-creator-lab approved these changes

2024-05-03 08:44 UTC, closed without merging