6213 Цуненко В. А. Лаб.3 Вар.1
itsecd/isb pull request #27
Opened 2024-03-12 15:40 UTC by Darowiin

Лабораторная работа состояла из 3 частей:
1. Генерация ключей гибридной системы:
результаты генерации находятся в папках [asymmetric_keys](https://github.com/Darowiin/isb/tree/lab3-var1/lab_3/asymmetric_keys) и [symmetric_keys](https://github.com/Darowiin/isb/tree/lab3-var1/lab_3/symmetric_keys).
2. Шифрование данных гибридной системой:
результат: [encrypted_text.txt](https://github.com/Darowiin/isb/blob/lab3-var1/lab_3/encrypted_text.txt).
3. Дешифрование данных гибридной системой:
результат: [decrypted_text.txt](https://github.com/Darowiin/isb/blob/lab3-var1/lab_3/decrypted_text.txt).

Программный код был объединен в [HybridEncryption](https://github.com/Darowiin/isb/blob/lab3-var1/lab_3/HybridEncryption.py).
Также была сделана единая точка входа в приложение с выбором режимов работы: [main.py](https://github.com/Darowiin/isb/blob/lab3-var1/lab_3/main.py).

2024-03-20 14:18 UTC, alxmcs requested changes
Остальные замечания будут от другого преподавателя

2024-03-20 14:18 UTC, alxmcs commented on lab_3/main.py
> +        )
То есть шанса пользователю сгенерировать ключи по своему пути, зашифровать/расшифровать свой собственный текст с указанием путей к своим собственным путям ты пользователю не даешь в основной точке входа в свое приложение?

Зачем ты пытаешь пользователя своего софта?

2024-03-20 14:18 UTC, alxmcs commented on lab_3/data_encryption.py
> +def text_encryption(text_path: str, private_key_path: str, symmetric_key_path: str, encryption_text_path: str) -> None:
Это очень плохая декомпозиция кода. Здесь в одной функции намешана и работа с файловыми потоками, и работа с симметричной криптографией, и работа с ассиметричной криптографией.

Гораздо более логично будет смотреться декомпозиция на
* модуль для работы с симметричной криптографией
* модуль для работы с ассиметричной криптографией
* модуль для вспомогательных операций - сериализации/десериализации ключей/текста
* модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системы, описанные в задании

Это смотрелось бы еще лучше с использованием объектно-ориентированного подхода, а не набора разрозненных функций (но это опционально)

2024-03-25 07:30 UTC, alxmcs requested changes

2024-03-25 07:30 UTC, alxmcs commented on lab_3/HybridEncryption.py
Ты зачем все в один класс засунул? Я же тебе в прошлом ревью подробно расписал декомпозицию кода.
Выделяй теперь из этого полотнища оставшиеся классы. `HybridEncryption` должен стать композитом.

Думал, раз прикладное программирование закончилось, можно откатываться обратно на уровень пещерного человека в написании кода?

2024-03-28 08:18 UTC, alxmcs requested changes

2024-03-28 08:18 UTC, alxmcs commented on lab_3/HybridEncryption.py
> +        self.key_len = key_len
Часть этих параметров  должны уйти в качестве полей в те классы, где они действительно должны быть - в `AsymmetricCryptography` и `SymmetricCryptography`.
А классы `AsymmetricCryptography` и `SymmetricCryptography` должны перестать быть статическими

2024-03-29 07:23 UTC, alxmcs approved these changes
👍

2024-03-29 09:17 UTC, Daria-creator-lab approved these changes

2024-05-17 07:15 UTC, closed without merging