6214 Чан Ван Куок Лаб.1 Вар.1
itsecd/isb pull request #28
Opened 2024-03-13 18:31 UTC by quocmoet195

Я писал функции для чтения и записи в файлом [read_file.py](https://github.com/quocmoet195/isb_Quoc/blob/lab1-var1/lab_1/read_file.py), [write_file.py](https://github.com/quocmoet195/isb_Quoc/blob/lab1-var1/lab_1/write_file.py)
Я писал функции для закодирования и расшифрования в файлом [encode.py](https://github.com/quocmoet195/isb_Quoc/blob/lab1-var1/lab_1/encode.py), [decode.py](https://github.com/quocmoet195/isb_Quoc/blob/lab1-var1/lab_1/decode.py)

2024-03-14 08:15 UTC, Daria-creator-lab commented
Код полностью скопирован у [6213 Цуненко В. А. Лаб.1 Вар.1](https://github.com/itsecd/isb/pull/28#top)

Переписать самостоятельно!

2024-03-18 07:26 UTC, alxmcs commented on lab_1/read_file.py
Объединить этот модуль

2024-03-18 07:26 UTC, alxmcs commented on lab_1/write_file.py
и этот модуль в один

2024-03-18 07:28 UTC, alxmcs commented on lab_1/encode.py
> +    step_path=os.path.join(abs_path,"part_1","step.txt")
Вынести эти параметры - путь к исходному тексту, путь к заширофваному тексту, номер итерации, а также путь к алфавиту, в json с настройками

2024-03-18 07:28 UTC, alxmcs commented on lab_1/encode.py
> +        raise Exception("Error when encode!")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:33 UTC, alxmcs commented on lab_1/encode.py
> +ALPHABET=read_file.read_from_file(alphabet_path)
Модульные константы так называются, потому что они постоянны при любом исполнении софта. 
Путь к алфавиту не является модульной константой. Он должен находиться в файле с настройками для запуска софта.

2024-03-18 07:33 UTC, alxmcs commented on lab_1/encode.py
> +        raise Exception("Error when encode text!\n")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:33 UTC, alxmcs commented on lab_1/decode.py
> +        raise Exception("Error when decode!")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:33 UTC, alxmcs commented on lab_1/decode.py
> +        raise Exception("Error when decode text!")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:33 UTC, alxmcs commented on lab_1/decode.py
> +        raise Exception("Error when creat and save to dictionary!")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:34 UTC, alxmcs commented on lab_1/read_file.py
> +       raise Exception("Failed to open file or file was not found!\n")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:34 UTC, alxmcs commented on lab_1/write_file.py
> +        raise Exception("Failed to write data or file was not found!\n")
Вывести в сообщении параметры объекта исключения

2024-03-18 07:34 UTC, alxmcs commented on lab_1/decode.py
> +def get_dict(input_path: str, output_path: str) -> None:
Нет докстринга

2024-03-18 07:34 UTC, alxmcs commented on lab_1/decode.py
> +def decode_text(original_text: str, key_path: str, decode_text: str) -> None:
Нет докстринга

2024-03-18 07:34 UTC, alxmcs commented on lab_1/encode.py
> +def encryption_text(input_path: str, output_path: str, step_path: str) -> None:
Нет докстринга

2024-03-18 07:34 UTC, alxmcs commented on lab_1/read_file.py
> +def read_from_file(path: str) -> str:
Нет докстринга

2024-03-18 07:34 UTC, alxmcs commented on lab_1/write_file.py
> +def write_to_file(path: str, data: str) -> None:
Нет докстринга

2024-03-18 07:35 UTC, alxmcs commented on lab_1/decode.py
> +    output_file=os.path.join(abs_path,"part_2","decoded_text.txt")
Вынести пути к файлам в отдельный json с параметрами для запуска софта

2024-03-18 07:36 UTC, alxmcs commented on lab_1/decode.py
> +def decode_text(original_text: str, key_path: str, decode_text: str) -> None:
Нарушение РЕР - неверное количество пустых строк

2024-03-23 04:05 UTC, quocmoet195 commented
Я добавил докстрингу, параметры объекта исключения и объединил модуль read_file и модуль write_file в один

2024-03-28 08:47 UTC, alxmcs requested changes

2024-03-28 08:47 UTC, alxmcs commented on lab_1/encode.py
> +        raise Exception(f"Error when encode!\n Exception:{ex}\n")
Вместо того, чтобы считать настройки из файла, тут ты их наоборот записываешь.
Код для инициализации настроек должен быть вынесен  отдельный модуль (если он тебе действительно необходим)
Тут должно происходить чтение параметров их файла настроек и запуск функций модуля

2024-04-01 06:49 UTC, Daria-creator-lab requested changes

2024-04-01 06:49 UTC, Daria-creator-lab commented on lab_1/part_2/path.py
> +    output_file_path=os.path.join(abs_path,"part_2","decoded_text.txt")
Никаких захардкоженных путей в коде быть не должно. 
Вы должны получать пути из файла с настройками settings.json

2024-04-01 06:49 UTC, Daria-creator-lab commented on lab_1/part_2/path.py
> +    return input_file_path, freq_dict_path, key_dict_path,output_file_path
Функция path_settings уже реализована у вас в [lab_1/part_1/path.py](https://github.com/itsecd/isb/pull/28/files#diff-0705184b38d272368c162d73e003dd2865cddb0e1fa18a99cdb7a20c505caea7)

Должна быть одна функция, которой в качестве параметра, передается путь до файла с настройками

2024-04-01 17:32 UTC, quocmoet195 commented
Я создал файлы Settings.py и Settings.json

2024-04-04 07:38 UTC, alxmcs approved these changes

2024-04-04 13:13 UTC, Daria-creator-lab approved these changes

2024-04-19 10:37 UTC, closed without merging