6211 Ушаков И.К. Лаб.3 Вар.6
itsecd/isb pull request #291
Opened 2024-06-06 01:06 UTC by micra07

Очень сильно намудрил с переносом кода из vs code, на github, поэтому расплодились лишние commit-ы.
Использовал argparse, чтобы предоставить пользователю возможность выбирать между режимами работы программы.
В файлах symmetric.py и asymmetric.py активно применял библиотеку cryptography
Файл for_work_with_files, представляет собой переделанный файл с аналогичным названием из моей первой лабораторной работы. 
В ряде методов написанных классов, предусмотрено различное их поведение в зависимости от выбранного режима работы

2024-06-06 17:33 UTC, ladyitsecurity requested changes
Написать в дискрипшенс алгоритм шифрования по варианту. 

Должна быть декомпозиция кода: разделение на несколько модулей (и все обернуто в классы): 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

Пока не соответствует.

2024-06-06 17:33 UTC, ladyitsecurity commented on lab_3/asymmetric.py
> +                                                 format=serialization.PublicFormat.SubjectPublicKeyInfo))
Разделить на разные функции.

2024-06-06 17:33 UTC, ladyitsecurity commented on lab_3/symmetric.py
> +from cryptography.hazmat.primitives import padding
Не соответствует PEP.

2024-06-06 17:33 UTC, ladyitsecurity commented on lab_3/symmetric.py
> +        return unpadded_text.decode('UTF-8')
Это что?

2024-06-06 18:56 UTC, micra07 commented on lab_3/symmetric.py
> +        return unpadded_text.decode('UTF-8')
В __pad_data происходит задание длины сообщения кратной длине зашифрованного блока, путем добавления отступов, а в __unpad происходит удаление этих самых отступов.

2024-09-25 08:14 UTC, ladyitsecurity approved these changes

2024-10-03 10:56 UTC, closed without merging