6214 Чан Куанг Минь Лаб.1 Вар.2
itsecd/isb pull request #30
Opened 2024-03-16 12:26 UTC by quangminh-202

Лаборатория состоит из 2 частей
    Часть 1
        Я использовал технику шифрования simple substitution cipher
    Часть 2
        Я использовал частотный анализ, чтобы найти ключ к 
        расшифровке cod2 text.txt

2024-03-16 18:00 UTC, Daria-creator-lab requested changes

2024-03-17 07:43 UTC, quangminh-202 commented
Task 1:
Я добавил dostrings и поместил русский алфавит в числовые переменные, написал больше функций декодирования, добавил обработку исключений, удалил ненужные файлы.
Task 2:
Я добавил dostrings, используя настройки файла.json, добавил обработку исключений.

2024-03-17 08:06 UTC, quangminh-202 commented on lab_1/task_2/decryption_code.py
> +import json
У меня есть вопросы, почему строка
 import json
 не соответствует pep

2024-03-18 07:04 UTC, Daria-creator-lab requested changes

2024-03-18 07:04 UTC, Daria-creator-lab commented on lab_1/task_2/decryption_code.py
> +                frequency_dict[char] = float(freq)
Получившиеся значения частотного анализа храните в формате json, тогда чтение и запись в файл будет происходить с помощью одной функции, что сократит вам код и повысит его читаемость

2024-03-18 07:04 UTC, Daria-creator-lab commented on lab_1/task_1/encryption_key.txt
> +В:Щ
ключ хранить в формате json, как в 2 задании

2024-03-18 07:26 UTC, quangminh-202 commented
Я удалил else, сохранил ключ упражнения 1 в файле json и скорректировал пустые строки в соответствии с pep

2024-03-19 14:37 UTC, Daria-creator-lab requested changes

2024-03-19 14:37 UTC, Daria-creator-lab commented on lab_1/task_1/simple_substitution_cipher.py
> +    return decrypted_text
Копия функции encrypt(text, key) с отличием в одной строке. Так делать не надо. Это нарушение SOLID.

Сделайте одну функцию, в которую в качестве параметра будет передаваться режим(шифрование или дешифрование).

*подсказка
используйте match/case для выбора режима

2024-03-19 14:37 UTC, Daria-creator-lab commented on lab_1/task_2/decryption_code.py
> +                            frequencies[char] = 1
это чрезмерно сложная реализация, попробуйте упростить

2024-03-19 14:37 UTC, Daria-creator-lab commented on lab_1/task_2/decryption_code.py
> +                output_file.write(decrypted_line + '\n')
проверьте количество отступов

2024-03-19 19:39 UTC, quangminh-202 commented
в задаче 1
Я скомпилировал две функции шифрования и расшифровал их в одну
 в задаче 2 
я сократил код, проверил отступы

2024-03-20 08:01 UTC, Daria-creator-lab requested changes

2024-03-20 08:01 UTC, Daria-creator-lab commented on lab_1/task_1/simple_substitution_cipher.py
> +            json.dump(key, file, ensure_ascii=False, indent=4)
Никаких захардкоженных путей в коде быть не должно. Используйте ваш файл с настройками [settings.json](https://github.com/itsecd/isb/pull/30/files#diff-61e47eb3ebcc316447b7d6ffb01debd13128ab56cbdb5845702d8a3df0058ee6)

2024-03-20 11:37 UTC, quangminh-202 commented
task_1: Я использовал файл .json, использовал enum и match / case

2024-03-21 05:57 UTC, Daria-creator-lab approved these changes

2024-04-04 13:09 UTC, closed without merging