6213 Корся Ева Дмитриевна Лаб.1 Вар.9
itsecd/isb pull request #31
Opened 2024-03-16 14:50 UTC by IvaKorsya

Лаборатория состоит из 2 частей
Часть 1
шифр Цезаря
Часть 2
частотный анализ

2024-03-16 18:21 UTC, Daria-creator-lab commented
добавить файл с зависимостями requirements.txt

2024-03-16 18:21 UTC, Daria-creator-lab requested changes

2024-03-16 18:21 UTC, Daria-creator-lab commented on lab_1/first_task/text_encryption.py
> +
не соответствует PEP

2024-03-16 18:21 UTC, Daria-creator-lab commented on lab_1/second_task/text_decryption.py
> +import sys
не соответствует PEP

2024-03-16 18:21 UTC, Daria-creator-lab commented on lab_1/first_task/work_w_files.py
> +        logging.error('error in write_file')
предусмотрена обработка исключений, но не передается информация об объекте исключения

2024-03-16 18:21 UTC, Daria-creator-lab commented on lab_1/first_task/text_encryption.py
> +            new_letters.append(char)
Вместо if/elif использовать match/case.

Если хотите проверить принадлежность символа к регистру, можно использовать функции isupper(), islower()

2024-03-16 18:21 UTC, Daria-creator-lab commented on lab_1/first_task/output.txt
> +н д уйужхдг чу, ьчу фхунцъуйнч. Пеп чурбпу уте фхуцткчцд, д зарулш ко зцк жкм шчеопн. Печецчхуще хемхемнчцд ткскйрктту.
Добавить расшифрованный текст для 1 задания

2024-03-18 07:09 UTC, Daria-creator-lab requested changes

2024-03-18 07:09 UTC, Daria-creator-lab commented on lab_1/first_task/text_encryption.py
> +
число пустых строк не соответствует PEP

2024-03-18 07:09 UTC, Daria-creator-lab commented on lab_1/second_task/text_decryption.py
> +
не соответствует PEP

2024-03-18 07:09 UTC, Daria-creator-lab commented on lab_1/second_task/text_decryption.py
> +            reverse=True)]
Уберите это из return, повысит читаемость кода

2024-03-18 11:48 UTC, IvaKorsya commented on lab_1/second_task/text_decryption.py
> +
![Screenshot from 2024-03-18 15-45-24](https://github.com/itsecd/isb/assets/115888475/a98bca38-8b5a-47ad-b605-480e00264215)
+ была до этого прогнана команда
autopep8 --in-place --aggressive --aggressive <filename>

2024-03-18 11:49 UTC, IvaKorsya commented on lab_1/second_task/text_decryption.py
> +
была прогнана autopep8 --in-place --aggressive --aggressive <filename>
![Screenshot from 2024-03-18 15-45-24](https://github.com/itsecd/isb/assets/115888475/aed36e2a-329c-4646-8c4b-ef99448fd1dd)

2024-03-19 14:28 UTC, Daria-creator-lab approved these changes

2024-03-19 14:28 UTC, Daria-creator-lab commented on lab_1/first_task/text_encryption.py
> +from work_w_files import read_file, write_file
между import и from должна быть пустая строка

2024-03-19 14:28 UTC, Daria-creator-lab commented on lab_1/requirements.txt
> +zipp==1.0.0
а вы где все это используете?

проверить зависимости

2024-03-20 06:17 UTC, IvaKorsya commented on lab_1/requirements.txt
> +zipp==1.0.0
я думала нужно сделать pip freeze, но забыла , что без venv подтянутся лишние пакеты (venv не создавала, тк доп библиотек не ставила). исправлю

2024-04-04 13:09 UTC, closed without merging