6214 Старцева А.В. Лаб. 1 Вар. 8
itsecd/isb pull request #33
Opened 2024-03-18 14:31 UTC by Annaprogrammer300

Данная лабораторная работа состоит из двух частей:

Я реализовала шифр методом транспонирования, но я брала не весь текст транспонировала, а алфавит, и получала ключ с помощью которого шифровала. Поэтому можно сказать что шифровала по ключу с частичным метод транспонирования. реализация находится в "task1".  Исходный, зашифрованный текст и ключ находится в папке first_task.

Расшифровка текста с помощью метода частотного анализа. Но возникли трудности с сопоставлением, так как частоты из заданного текста не полностью совпадают с обобщенными данными, поэтому я чучуть вручную подкорректировала получившийся ключ по примеру из методички. Реализация находится в "task2". Исходный, зашифрованный текст, результат частотного анализа,  и ключ находится в папке second_task. Поэтому в этой папке два ключа и два расшифрованных текста. Итоговый ключ и расшифровка записаны в "text_key" и  "text_decryption" соответственно
Функции для работа с файлами json и txt находится в "works_files"

2024-03-20 07:41 UTC, Daria-creator-lab requested changes

2024-03-20 07:41 UTC, Daria-creator-lab commented on lab_1/task1.py
> +
Никаких захардкоженных магических чисел в коде быть не должно.

2024-03-20 07:41 UTC, Daria-creator-lab commented on lab_1/task1.py
> +                os.path.join('first_task', 'decryption.txt'))
Никаких захардкоженных путей в коде быть не должно.
Используйте файл с настройками

2024-03-20 07:41 UTC, Daria-creator-lab commented on lab_1/task1.py
> +    write_files(path_decryption, result)
Функции encrypt и decrypt почти идентичны. Так делать не надо, это нарушение SOLID.
Объедините эту функцию и encrypt, и передавайте режим(шифрование/дешифрование) в качестве параметра.

*подсказка 
для режима используйте Enum и match/case

2024-03-20 07:41 UTC, Daria-creator-lab commented on lab_1/task2.py
> +                os.path.join('second_task', 'text_decryption.txt'))
аналогично

2024-03-20 07:41 UTC, Daria-creator-lab commented on lab_1/requirements.txt
> +soupsieve==2.5
а вы где это используете?

2024-03-20 07:41 UTC, Daria-creator-lab commented
почистить файлы 
<img width="220" alt="image" src="https://github.com/itsecd/isb/assets/73466150/41538902-5123-40b7-b109-db1ad898cd11">

2024-03-24 21:29 UTC, Annaprogrammer300 commented on lab_1/requirements.txt
> +soupsieve==2.5
нигде не использую :(

2024-03-29 06:42 UTC, Daria-creator-lab approved these changes

2024-04-19 10:19 UTC, closed without merging