6212-100503D Сайдашев Андрей Алексеевич Лаб.1 Вар.9
itsecd/isb pull request #34
Opened 2024-03-18 16:05 UTC by klon-22800

Лабораторная работа состоит из двух частей.
Кодирование и расшифровка текста методом моноалфавитной замены. 
Лабораторная выполнена с созданием GUI на PyQt5.
Каждая часть лабораторной находится в соответствующих папках.

2024-03-22 12:06 UTC, ladyitsecurity requested changes
Наименования файлов не соответствуют PEP.

2024-03-22 19:01 UTC, klon-22800 commented on lab_1/lib.py
> +    return res
В случае если бы попался знак препинания, то ничего страшного не произошло бы, просто пользователь получит всплывающее окно с сообщением о некорректности ключа. Тем не менее функции переписаны.

2024-03-25 12:20 UTC, ladyitsecurity requested changes

2024-03-25 12:20 UTC, ladyitsecurity commented on lab_1/lib.py
> +            return data
То есть файл все таки не закрываем?

2024-03-25 12:20 UTC, ladyitsecurity commented on lab_1/lib.py
> +            return data
Аналогично.

2024-03-25 12:20 UTC, ladyitsecurity commented on lab_1/lib.py
> +            res += letter
Это предскажуемый результат, поэтому не нужно его обрабатывать как исключение. Есть if и else, например.. А если хотите исключения, то остановите все вообще, если нет в ключе такого, а не делайте вид, что все норм.

2024-03-25 12:20 UTC, ladyitsecurity commented on lab_1/lib.py
> +            res += letter
Аналогично.

2024-03-27 21:57 UTC, klon-22800 commented on lab_1/lib.py
> +            res += letter
Заменено на if else

2024-03-28 19:05 UTC, ladyitsecurity approved these changes

2024-05-24 08:12 UTC, closed without merging