6213 Будюк В.А. Лаб.1 Вар.4
itsecd/isb pull request #4
Opened 2024-02-12 05:19 UTC by Nibuku

Лабораторная работа состоит из двух частей: кодирование текста с помощью шифра цезаря и декодирование методом частотного анализа. Код разделен на три части: модуль для работы с файлами (открытие, запись и форматирование), модуль по первому заданию и по второму. Результаты работы есть в папках task1 и task2

p.s. понимаю, что функции coding и decoding  в сaesar_cipher почти одинаковые, но не уверена, надо ли их в одну соединить- т.к. тогда одна функция будет делать две задачи ,но они достаточно примитивные, с другой стороны...

2024-02-12 11:34 UTC, Daria-creator-lab requested changes
проверьте код

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/freq_cipher.py
> +    data = decoding("Ч", "ц", data, os.path.join("lab_1", "task2", "keys.txt"), key)
написать дополнительную функцию с параметрами: исходный алфавит = "MX4...>ч", ключ = "*н...ц" ,путь и тд, которая будет вызывать функцию decoding

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/open_save_part.py
> +        text_file.close()
используйте with open, как в коде выше

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/task1/key.txt
Переведите ключ в другой формат. 
Лучше сделать его в виде json.
Методы, работающие с этим ключом, также должны измениться.  

Для второго задания аналогично.

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/freq_cipher.py
> +    )
параметры должны получаться из файла с настройками (или используйте argparse)

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/сaesar_cipher.py
> +from open_save_part import open_file, write_data, dict_save
не соответствует PEP (проверить остальной код)

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/open_save_part.py
> +        logging.error(f"Failed to formatting data\n")
бесполезный f-string 
Проверить остальной код.

2024-02-12 11:34 UTC, Daria-creator-lab commented on lab_1/freq_cipher.py
> +        my_dict[i] = round((data.count(i) / len(data)), 5)
почему здесь 5? что округляем?

2024-02-12 15:49 UTC, Nibuku commented
по изменениям: 
1)везде использовала json как файл с настройками
2) написала utility, но она не вызывает decoding, т.к. decoding изменяет по одному символу и фиксирует изменения сразу же в словарь с ключом (т.к. дешифруя по частотному анализу нужно было следить как изменяется текст и записывать уже измененные буквы). 
А utility уже использует ключ для быстрой дешифровки: парсит json и заменяет циклом все буквы (и отдельно заменяет "_" на пробел, т.к. джисон не принимает "  " за "").
и я немного запуталась с порядком библиотек по PEP, т.к. они все стандартные, но сейчас вроде бы правильно

2024-02-13 09:53 UTC, alxmcs requested changes

2024-02-13 09:53 UTC, alxmcs commented on lab_1/сaesar_cipher.py
> +def decodding(path: str, new_path: str, step: int) -> None:
<img src="https://github.com/itsecd/isb/assets/70561974/8a2a88b9-93e0-4a53-9663-2f5037d2e265" width=300>

Я просто проходил мимо, но решил напомнить, что декодирование и дешифрование - не одно и то же.
Объяснять это самому мне лень, так что вот [ссылка](https://stackoverflow.com/a/32202648)

2024-02-13 10:57 UTC, Nibuku commented on lab_1/сaesar_cipher.py
> +def decodding(path: str, new_path: str, step: int) -> None:
![cat-water](https://github.com/itsecd/isb/assets/127037096/4e561d78-8a4e-429e-860b-f370010f4b67)
Извиняюсь, прочитала и разобралась-все исправила

2024-02-14 09:43 UTC, alxmcs approved these changes

2024-02-14 09:56 UTC, Daria-creator-lab approved these changes

2024-04-04 13:02 UTC, closed without merging