6214 Чан Ван Куок Лаб.2 Вар.1
itsecd/isb pull request #40
Opened 2024-03-21 17:29 UTC by quocmoet195

Я писал функции для генерации случайной последовательности [creat_random.cpp](https://github.com/quocmoet195/isb_Quoc/blob/lab2-var1/lab_2/creat_random.cpp)
Я писал функции для  проверки с помощью частотного побитового теста [task_a.py](https://github.com/quocmoet195/isb_Quoc/blob/lab2-var1/lab_2/task_a.py)
Я писал функции для  проверки с помощью теста на одинаковые подряд идущие биты [task_b.py](https://github.com/quocmoet195/isb_Quoc/blob/lab2-var1/lab_2/task_b.py)
Я писал функции для  проверки с помощью теста на самую длинную последовательность единиц в блоке [task_c.py](https://github.com/quocmoet195/isb_Quoc/blob/lab2-var1/lab_2/task_c.py)

2024-03-29 09:16 UTC, Daria-creator-lab requested changes

2024-03-29 09:16 UTC, Daria-creator-lab commented on lab_2/task_c.py
> +    pi3 = 0.1875
вынести в константу pi = [0.2148, 0.3672 ...]

2024-03-29 09:16 UTC, Daria-creator-lab commented on lab_2/task_a.py
Необходимо сделать отчет по результатам тестов.
Все значения P_value для каждого теста должны храниться в отдельном файле.

2024-03-29 12:46 UTC, quocmoet195 commented
Я отредактировал тестовые функции, объединил их в один файл NIST.py и сделать отчет по результатам тестов.

2024-04-01 08:01 UTC, Daria-creator-lab requested changes

2024-04-01 08:01 UTC, Daria-creator-lab commented on lab_2/result.json
По результатам тестов NIST сформировать отчет с выводами о случайности последовательностей

2024-04-01 19:46 UTC, quocmoet195 commented
Я выполнил все тесты с помощью случайной последовательности C++ и Java.
Я отредактировал код в соответствии со стандартами PEP.
Я определил число Пи как константу и создал отчет

2024-04-04 13:40 UTC, Daria-creator-lab requested changes

2024-04-04 13:40 UTC, Daria-creator-lab commented on lab_2/NIST.py
> +        file.write(json.dumps({"Frequency bit test":P1, "Consecutive bits test": P2, "Longest sequence of ones test": P3}, indent=1))
добавить обработку исключений

2024-04-04 13:40 UTC, Daria-creator-lab commented on lab_2/NIST.py
> +        file.write(json.dumps({"Frequency bit test":P1, "Consecutive bits test": P2, "Longest sequence of ones test": P3}, indent=1))
добавить обработку исключений

2024-04-04 13:40 UTC, Daria-creator-lab commented on lab_2/NIST.py
> +    P1, P2, P3 = calculate(bits_java)
замените названия переменных
переменные P1, P2, P3 уже объявлены ранее

2024-04-04 13:40 UTC, Daria-creator-lab commented on lab_2/NIST.py
> +
между функциями должно быть 2 пустых строки 
исправьте везде

2024-04-05 17:07 UTC, quocmoet195 commented
Я добавил исключение и исправил имена переменных и стандарты PEP.

2024-04-08 07:05 UTC, Daria-creator-lab approved these changes

2024-04-19 11:00 UTC, closed without merging