6211 Маркелов Родион Алексеевич Лаб.1 Вар.3
itsecd/isb pull request #43
Opened 2024-03-22 18:15 UTC by RoodionMarkelov

2024-03-25 12:06 UTC, ladyitsecurity requested changes
Почистить проект. Подумать об исключениях. Дописать параметры во всех докстрингах.

2024-03-25 12:06 UTC, ladyitsecurity commented on lab_1/task2/analysis.py
> +    text = text.replace("Ь", "щ")
Я говорила на 1 лабе, что так не делаем. Используем для этого цикл - это тоже декомпозиция!

2024-03-25 12:06 UTC, ladyitsecurity commented on .idea/inspectionProfiles/profiles_settings.xml
убрать

2024-03-25 12:06 UTC, ladyitsecurity commented on .idea/isb_lab.iml
в

2024-03-25 12:06 UTC, ladyitsecurity commented on .idea/misc.xml
гит

2024-03-25 12:06 UTC, ladyitsecurity commented on .idea/modules.xml
игнор

2024-03-28 17:21 UTC, ladyitsecurity requested changes
Теперь вылезла папка .idea. Тоже нужно убрать

2024-03-28 17:21 UTC, ladyitsecurity commented on lab_1/task1/encryption.py
> +        print(f"Произошла ошибка в функции send_encryption_text: {e}")
Исправьте этот ужас... Все в кучу и неправильно.

2024-03-28 17:21 UTC, ladyitsecurity commented on lab_1/task1/key_for_task1.py
> +
А вот это кому?

2024-04-05 14:45 UTC, ladyitsecurity requested changes

2024-04-05 14:45 UTC, ladyitsecurity commented on lab_1/task1/encryption.py
> +                print(f"Произошла ошибка в функции send_encryption_text: {e}")
Не исправлено.

2024-04-24 12:52 UTC, ladyitsecurity commented on lab_1/task1/encryption.py
> +                print(f"Произошла ошибка в функции send_encryption_text: {e}")
И добавьте description описание лабораторной работы и каким вариантом шифровали.

2024-04-24 14:46 UTC, RoodionMarkelov commented on lab_1/task1/encryption.py
> +                print(f"Произошла ошибка в функции send_encryption_text: {e}")
Извините, но этот комит из ветки main, а не lab1-var3, это не та ветка. Я сначала комитил в эту ветку, но потом вы сказали создать новую

2024-06-14 15:52 UTC, closed without merging