6213 Корся Ева Дмитриевна Лаб.2 Вар.9
itsecd/isb pull request #45
Opened 2024-03-24 12:48 UTC by IvaKorsya

nist tests

2024-03-29 07:34 UTC, Daria-creator-lab commented
> nist tests

Опишите подробнее, что вы делали в лабе

2024-03-29 07:46 UTC, Daria-creator-lab requested changes

2024-03-29 07:46 UTC, Daria-creator-lab commented on lab_1/.gitignore
убрать лишние файлы

2024-03-29 07:46 UTC, Daria-creator-lab commented on lab_2/result.md
> +    Тест на самую длинную последовательность единиц в блоке - 0.162662119435677
обновите результаты

2024-03-29 07:46 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +PI_I = {1: 0.2148, 2: 0.3672, 3: 0.2372, 4: 0.1875}
![image](https://github.com/itsecd/isb/assets/73466150/20d6a26f-b9d5-4bee-9448-229ccad7ef7e)

2024-03-31 07:24 UTC, IvaKorsya commented
В лабораторной работе нужно было сгенерировать псевдослучайные последовательности с помощью стандартных ГПСЧ языков С/С++ и Java. Реализовать три теста линейки NIST и проверить с их помощью сгенерированные последовательности, а также сделать вывод по полученным результатам и написать отчет по выполненной работе.

2024-03-31 07:28 UTC, IvaKorsya commented
возник конфликт при отчистке /lab_1 (видимо когда я создавала новую ветку нужно было делать из main, а я сделала на ветке lab1_var9, и все файлы с 1 ветки оказались во второй), я забыла про README.md и удалила вообще все файлы...можно не решать его, все равно мерджить не надо будет?

2024-04-01 08:13 UTC, Daria-creator-lab requested changes

2024-04-01 08:13 UTC, Daria-creator-lab commented on lab_2/result.md
> +    Тест на самую длинную последовательность единиц в блоке - 0.138143896280847
обновите результаты!

Посмотрите вывод вашей функции perform_frequency_bit_test для последовательности cpp: "11000111111010000000111101010011101110011010001010101011111101110001011100101001000000011111101011111011001110101000011000110110"

2024-04-04 14:07 UTC, Daria-creator-lab requested changes

2024-04-04 14:07 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +              for i in range(1, len(PI_I))])
неверно вычисляется хи

2024-04-12 08:04 UTC, Daria-creator-lab approved these changes

2024-04-19 04:57 UTC, closed without merging