6211 Пихуров М.А. Лаб.1 Вар.7
itsecd/isb pull request #49
Opened 2024-03-27 19:10 UTC by moter1026

2024-03-28 11:45 UTC, ladyitsecurity requested changes
Нет обработки исключений. Названия функций не соответствуют PEP. Для первой лабы я, может быть, приму такой UX/UI, но вообще в дискашенс написано, что надо сделать через аргпарс или графический интерфейс...

2024-03-28 16:36 UTC, moter1026 commented
Изменил названия функций, добавил обработки исключений. UI не переделал, потому по задумке у меня было, чтобы пользователь мог выбирать те или иные действия в процессе выполнения программы. В следующей лабораторной приму к сведению и не буду создавать подобный алгоритм.

2024-04-05 13:00 UTC, ladyitsecurity requested changes

2024-04-08 09:53 UTC, ladyitsecurity requested changes

2024-04-08 09:53 UTC, ladyitsecurity commented on lab_1/task_1/index.py
> +    write_file(FILES["text_end"], encrypt_text)
Круто, что вы используете Json. Но проблема хардкода то осталась.

2024-04-08 09:53 UTC, ladyitsecurity commented on lab_1/task_1/index.py
> +
Много.

2024-04-08 09:53 UTC, ladyitsecurity commented on lab_1/task_1/work_with_json.py
> +    return data
Заодно вот это можно внести в другой, уже существующий файл, потому что 8 строк кода в отдельный файл - плохо.

2024-04-08 09:53 UTC, ladyitsecurity commented on lab_1/task_2/consts.py
> +
Зачем это здесь?

2024-04-08 09:53 UTC, ladyitsecurity commented on lab_1/task_2/functions_for_task2.py
> +    возвращает первые count самых популярных знач. """
Кстати, это можно написать в одну строчку.

2024-04-08 09:53 UTC, ladyitsecurity commented on lab_1/task_2/work_with_json.py
> +    return data
Аналогично. А еще если один и тот же файл без изменений используется в двух местах, лучше его не копировать, а просто вынести на уровень выше и импортировать в нужных местах.

2024-04-08 11:55 UTC, moter1026 commented on lab_1/task_1/index.py
> +    write_file(FILES["text_end"], encrypt_text)
Не понимаю о чём вы. Где здесь проблема хардкора

2024-04-08 11:56 UTC, moter1026 commented on lab_1/task_2/functions_for_task2.py
> +    возвращает первые count самых популярных знач. """
![image](https://github.com/itsecd/isb/assets/76918726/57140965-2454-406e-948c-906eb9103737)
а по PEP
![image](https://github.com/itsecd/isb/assets/76918726/d1d5a609-bf4f-49d2-9639-7f8053eed0a7)
Поэтому я разделил на несколько строк

2024-04-08 11:57 UTC, moter1026 commented on lab_1/task_2/work_with_json.py
> +    return data
Реализовал это, но пришлось среди import-ов вставлять sys.path.insert(...)
![image](https://github.com/itsecd/isb/assets/76918726/20570eb5-8aea-4e47-976a-a10f64d896f7)
Не знаю насколько это можно так писать

2024-04-08 12:46 UTC, moter1026 commented on lab_1/task_1/index.py
> +    write_file(FILES["text_end"], encrypt_text)
Не понимаю почему так неправильно, но я исправил

2024-04-08 12:48 UTC, moter1026 commented on lab_1/task_2/work_with_json.py
> +    return data
При исправлении хардкода файлы изменились. Теперь они не одинаковы

2024-04-08 16:11 UTC, ladyitsecurity commented on lab_1/task_2/work_with_json.py
> +    return data
Тогда это должно навести на мысль о том, что писать 2 разных файла, чтобы прочитать 2 несчастных маленьких json`а - это слишком жирно для таких небольших структур данных.

2024-04-08 16:14 UTC, ladyitsecurity commented on lab_1/task_2/functions_for_task2.py
> +    возвращает первые count самых популярных знач. """
Во-первых, не нужно писать 30 строк кода, когда можно написать 1. Велосипед придумали один раз и этого достаточно. Во-вторых, можно:

1. сделать перенос в этой строчке
2. одной строкой отсортировать, а потом обрезать сколько нужно и вернуть.

2024-04-08 16:16 UTC, ladyitsecurity requested changes
Ответила в комментариях к прежнему PR.

2024-04-08 20:18 UTC, moter1026 commented on lab_1/task_2/work_with_json.py
> +    return data
Поменял. Вынес work_with_json в родительскую директорию, в уже существующих файлах для каждого задания сделал функции для возвращения необходимых переменных.

2024-04-10 06:06 UTC, ladyitsecurity requested changes

2024-04-10 06:06 UTC, ladyitsecurity commented on lab_1/task_2/functions_for_task2.py
> +import work_with_json
Это что?

2024-04-10 06:06 UTC, ladyitsecurity commented on lab_1/task_2/index.py
> +    try:
Не соответствует PEP.

2024-04-10 06:32 UTC, moter1026 commented on lab_1/task_2/functions_for_task2.py
> +import work_with_json
Вы мне сказали, что нет никакого смысла создавать 2 отдельных файла, чтобы прочитать два маленьких файла json. Эти 2 файла были для разных заданий, в разных папках. 

Соответственно, чтобы был один файл,  я вынес его в родительскую директорию. А добавлять модули не из дочерних папок это проблема в питоне, одно из решений которых я использовал здесь. 

Я искренне не понимаю, что вы от меня хотите добиться, и если реально хотите, чтобы я что-то определённое сделал, то сообщите об этом более чётко.

Я не сопротивляюсь вносить изменения, но для меня непонятно почему кого-то с теми "проблемами", которые вы нашли у меня, вы пропускаете других

2024-04-10 06:32 UTC, moter1026 commented
Ответил в комментарии выше

2024-04-10 11:12 UTC, ladyitsecurity commented on lab_1/task_2/functions_for_task2.py
> +import work_with_json
Это называется [относительный импорт](https://docs.python.org/3/reference/import.html#package-relative-imports:~:text=%D0%BD%D0%B5%D0%BC%D0%B5%D0%B4%D0%BB%D0%B5%D0%BD%D0%BD%D0%BE%20%D0%BF%D1%80%D0%B5%D0%BA%D1%80%D0%B0%D1%89%D0%B0%D0%B5%D1%82%20%D0%B5%D0%B3%D0%BE.-,5.7.%20%D0%9E%D1%82%D0%BD%D0%BE%D1%81%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%20%D0%BF%D0%B0%D0%BA%D0%B5%D1%82%D0%BE%D0%B2,-%C2%B6)

2024-04-10 16:56 UTC, ladyitsecurity approved these changes

2024-04-26 05:55 UTC, closed without merging