6211 Ушаков И.К. Лаб.1 Вар.4
itsecd/isb pull request #52
Opened 2024-03-28 15:58 UTC by micra07

В данной работе для выполнения первого задания я использовал шифр Виженера(С учётом буквы Ё при шифровании).
Все файлы, для первого задания лежат в папке task1, а для второго - в task2. 
Во втором задании расшифрованный текст специально содержит все переходы на новую строку, как это было сделано в исходном файле code4.txt

2024-03-28 17:34 UTC, ladyitsecurity requested changes

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task1/for_work_with_file.py
> +
не соответствует PEP.

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task1/for_work_with_file.py
> +
Не соответствует PEP (и не только тут).

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task1/task1.py
> +alphabet = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'
Все константы выносим в отдельный файл.

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task1/task1.py
> +from for_work_with_file import save_to_file, read_from_file, save_to_json_file
Не соответствует PEP.

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task1/task1.py
> +    key = 'лист'
А в отдельном файле тогда что?

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task1/task1.py
> +
Ничего захардкоженного быть не должно. Выносим в отдельный файл.

2024-03-28 17:34 UTC, ladyitsecurity commented on lab_1/task2/task2.py
> +    save_to_file('lab_1/task2/decrypted_text.txt', text)
Аналогично.

2024-05-02 17:31 UTC, ladyitsecurity requested changes

2024-05-02 17:31 UTC, ladyitsecurity commented on lab_1/task1/task1.py
> +from constants import PATH
Не соответствует PEP.

2024-05-02 17:31 UTC, ladyitsecurity commented on lab_1/task2/for_work_with_file.py
Одинаковый код для двух задач. Вынести на уровень выше и импортировать там, где надо. Если надо, сделать единую точку входа для обоих заданий.

2024-05-02 17:31 UTC, ladyitsecurity commented on lab_1/task2/task2.py
> +import for_work_with_file
Не соответствует PEP.

2024-05-02 17:31 UTC, ladyitsecurity commented on lab_1/task2/task2.py
> +                continue
Ненужные действия.

2024-05-02 17:31 UTC, ladyitsecurity commented on lab_1/task2/task2_key.py
Не соответствует PEP.

2024-05-16 11:30 UTC, ladyitsecurity requested changes

2024-05-16 12:12 UTC, micra07 commented on lab_1/task1.py
> +from constants1 import PATH
Здравствуйте, можете пожалуйста подсказать, что именно не соответствует PEP, я уже несколько раз перечитывал материалы по PEP, пробовал группировать все impirt-ы, сделал между группами пустую строку, но я не понимаю, что именно не удовлетворяет требованиям PEP

2024-05-16 12:13 UTC, micra07 commented on lab_1/task2/task2_key.py
Не хватает пустой строки с пробелом, я правильно понимаю?

2024-06-02 07:54 UTC, ladyitsecurity approved these changes

2024-06-06 09:04 UTC, closed without merging