6211 Фролкин Н. С. Лаб.2 Вар.2
itsecd/isb pull request #54
Opened 2024-03-29 03:05 UTC by nick-vivo

Нужно было создать три линейки тестов NIRS. Ввиду отсутсвия в java стандартной библиотеки интегралов, функций exp и тд, всё было реализовано с нуля. Сам код написан на java языке. 

Если у вас будет время, то прошу посмотреть также генератор случайных чисел Fortuna. Конкретно меня интересует бессмысленный код - то что не приносит в алгоритм "случайности".

2024-03-29 21:29 UTC, nick-vivo commented
Язык реализации был изменён из-за требований...

2024-04-01 13:08 UTC, ladyitsecurity requested changes
Еще раз проверить на соответствие PEP.

2024-04-01 13:08 UTC, ladyitsecurity commented on lab_2/src/tests.py
> +def longest_sequence_ones_block_eight_test(array_bits: str) -> float:
Не соответствует PEP.

2024-04-01 13:08 UTC, ladyitsecurity commented on lab_2/src/tests.py
> +def identical_consecutive_bits_test(array_bits: str) -> float:
Не соответствует PEP.

2024-04-01 13:43 UTC, nick-vivo commented on lab_2/src/consts.py
> +    return key
функция hash возращает одну из теоретических проб, выносить её за константы, где не будут содержаться эти пробы - глупость. Так как она связана с пробами в первую очередь

2024-04-05 12:27 UTC, ladyitsecurity requested changes

2024-04-05 12:27 UTC, ladyitsecurity commented on lab_2/src/probies.py
Я вроде уже говорила, что это обычная функция, и что не надо выносить одну функцию в отдельный файл. Декомпозиция - это РАЗУМНОЕ разделение кода. То, что функция выдает 1 из 4 вариантов, не говорит о том, что она чем-то важнее других функций.

2024-04-05 12:29 UTC, ladyitsecurity commented
И именуйте коммиты правильно, пожалуйста. Если вы используете нестандартный язык для таких вещей, это не должно стать проблемой для остальных, поэтому давайте унифицировать подобные вещи. И кстати, о языке, на котором нужно писать - я проверила ридми в репозитории, и там четко сказано, что код должен соответствовать PEP, что должно было навести на мысль о выборе языка программирования для всех лабораторных работ.

2024-04-05 15:13 UTC, nick-vivo commented on lab_2/src/probies.py
объясните мне тогда пожалуйста почему я не могу вынести эту функцию в отдельный файл или файл с константами. она же по сути связана с пробами. Мне этот момент не ясен. Конкретно она возвращает один номер из теоретической пробы, если мы положим её в файл с тестами, а номера констант поставим произвольные, не забудем ли мы при это изменить эту функцию? Допустим при добавлении новых проб, не меняя при этом основного функционала функции

2024-04-05 15:15 UTC, nick-vivo commented
> И именуйте коммиты правильно, пожалуйста. Если вы используете нестандартный язык для таких вещей, это не должно стать проблемой для остальных, поэтому давайте унифицировать подобные вещи. 

Есть ли в этом смысл если задачу делает каждый студент отдельно и сложность задачи не настолько большая, чтобы мне нужно было возвращаться к своим прежним коммитам???

2024-04-05 16:57 UTC, nick-vivo commented
постараюсь писать коммиты, хотя прежние и так содержат всю нужную информацию для понимания того что было в нём сделано

2024-04-08 16:03 UTC, ladyitsecurity commented on lab_2/src/probies.py
Потому что в теории это можно вообще не выносить в отдельную функцию. И сам факт того, что это ФУНКЦИЯ, должно намекать на то, что происходят какие-то действия и выдается разный результат при разных входных параметрах. И это никак не похоже на константу... Это вспомогательная для теста функция. Поэтому она должна быть с ним в одном файле, чтобы другой человек при просмотре вашего кода смог понять, для чего эта функция, и что они связаны с тестом. Тест выполняет одну задачу. То, что вы решили выделить в отдельную функцию ее часть - окей. Но тогда ее не нужно разрывать на несколько файлов в разных местах.

2024-04-08 16:05 UTC, ladyitsecurity commented
> постараюсь писать коммиты, хотя прежние и так содержат всю нужную информацию для понимания того что было в нём сделано

Неважно, что было раньше, может, вас взломали и загрузили всякую чушь. Адекватность должна оставаться всегда, как и стиль оформления коммитов. Это база разработчиков.

2024-04-08 16:07 UTC, ladyitsecurity approved these changes

2024-06-06 13:32 UTC, closed without merging

2024-11-27 10:47 UTC, nick-vivo commented
прошу удалить репозиторий с сервера. происходит компрометация конф данных