6211 Фролкин Н. С. Лаб.1 Вар.2
itsecd/isb pull request #55
Opened 2024-03-29 03:22 UTC by nick-vivo

В данной лабораторной работе нужно было перевести шифр простой замены, а также создать свой алгоритм шифрации текста (или выбрать из предложенных). Решения первой задачи представлены в Solution1, а второй в Solution2. Было реализовано ui - консольное приложение. Что нужно вписать в терминал для шифрации и перевода текстов указано в README.md

За последние две недели я не получал новых правок по коду, поэтому было решено пересоздать пулл. Вероятно из-за того что код находится на "дне" либо из-за несоотвествия кода каким-то требованиям. Если такие присутствуют, то прошу перепроверить работу и явно указать мне правки.

2024-03-29 17:22 UTC, nick-vivo commented
Код был переписан в соотвествии с требованиями...

2024-03-29 21:17 UTC, nick-vivo commented
От консольного приложения было приложения было принято отказаться. просто запускаете файл solution.py...

2024-04-01 12:52 UTC, ladyitsecurity requested changes
Не нашла функции поиска частот для исходного текста 2 задания (по которой нужно было декодировать сообщение).

2024-04-01 14:31 UTC, nick-vivo commented
Всё это было в изначальной версии... был сделан специальный класс для нормальной дешифрации, но так урезать его функционал...

2024-04-01 15:27 UTC, nick-vivo commented
функции в файле src.mono...

2024-06-06 13:31 UTC, closed without merging