6211 Семенова Александра Павловна Лаб.1 Вар.9
itsecd/isb pull request #59
Opened 2024-03-30 10:46 UTC by Sapdotten

В ходе работы был создан класс для шифровки и дешифровки текста методом маршрутной транспозиции. Текст записывается в таблицу шифрования "змейкой" таким образом, что в каждый четный столбец его отрывок записывается сверху вниз, а в каждый нечетный наоборот - снизу вверх. Приведен пример шифрования и дешифрования отрывка текста.
Так же был был расшифрован отрывок зашифрованного текста методом частотного анализа, а также получен ключ, по которому этот текст расшифровывается.

2024-04-01 12:29 UTC, ladyitsecurity requested changes

2024-04-01 12:29 UTC, ladyitsecurity commented on lab_1/task_1/main.py
> +
А здесь не может возникнуть исключений?

2024-04-01 12:29 UTC, ladyitsecurity commented on lab_1/task_2/main.py
> +        f.write(text)
Аналогично

2024-04-05 12:37 UTC, ladyitsecurity requested changes

2024-04-05 12:37 UTC, ladyitsecurity commented on lab_1/task_1/main.py
> +from constants import *
Кстати, не соответствует PEP.

2024-04-05 12:37 UTC, ladyitsecurity commented on lab_1/task_1/main.py
> +        return self._encode(text)
А в чем глобальная разница? И выбраны такие названия функций? (именно разница между названиями)

2024-04-05 12:37 UTC, ladyitsecurity commented on lab_1/task_1/main.py
> +    encoding(encoding_key)
Ключ храним в отдельном файле, об этом написано в методичке. Ключ, исходный текст и зашифрованный текст. Аналогично для другой части задания.

2024-04-05 12:37 UTC, ladyitsecurity commented on lab_1/task_2/main.py
> +from copy import copy
Аналогично.

2024-04-05 15:53 UTC, Sapdotten commented on lab_1/task_1/main.py
> +from constants import *
Исправила

2024-04-05 15:55 UTC, Sapdotten commented on lab_1/task_1/main.py
> +        return self._encode(text)
_decode предназначен для использования внутри класса как protected метод, decode - доступен вне класса.

2024-04-05 15:55 UTC, Sapdotten commented on lab_1/task_1/main.py
> +    encoding(encoding_key)
Исправлено

2024-04-05 15:55 UTC, Sapdotten commented on lab_1/task_2/main.py
> +from copy import copy
Исправлено

2024-04-26 07:13 UTC, closed without merging