6214 Шаменков М.А. Лаб.3 Вар.6
itsecd/isb pull request #61
Opened 2024-03-31 08:02 UTC by Maximprogrammer58

В данной лабораторной работе была реализована гибридная криптосистема. Использованы два вида шифрования: асимметричный алгоритм RSA, симметричный алгоритм SEED. Были реализованы 3 независимых класса: .KeyGenerator(генерация ключей шифрования), Encryption(Шифрование данных), Decryption(Дешифрование данных) . Работа с файлами организована с помощью модуля serialize_and_deserialize.py. Взаимодействие с пользователем реализовано через argparse в main.py.

2024-04-08 07:40 UTC, Daria-creator-lab requested changes

2024-04-08 07:40 UTC, Daria-creator-lab commented on lab_3/main.py
> +
а что тут может сделать пользователь? 

дайте ему возможность 

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам

2024-04-08 07:40 UTC, Daria-creator-lab commented on lab_3/modules/Encryption.py
> +        return self.__symmetric_key
такая функция уже есть в lab_3/modules/Decryption.py

Попробуй разделить не на модули для шифрование/дешифрование, а на модули для работы с симметричной/ассиметричной криптографией

2024-04-12 19:25 UTC, Maximprogrammer58 commented on lab_3/modules/Encryption.py
> +        return self.__symmetric_key
Переделал. Просто я изначально планировал сделать 3 независимых блока (класса): генерация ключей, шифрование и дешифрование

2024-04-15 15:55 UTC, Daria-creator-lab approved these changes

2024-04-19 09:38 UTC, closed without merging