6213 Журавлев С.А. Лаб.2 Вар.5
itsecd/isb pull request #62
Opened 2024-03-31 10:51 UTC by fl1n4

В ходе лабораторной работы были сгенерированы псевдослучайные бинарные последовательности с помощью стандартных ГПСЧ языков Java и C++.
Для проверки качества генераторов были применены тесты на случайность из набора тестов NIST.

2024-04-01 08:39 UTC, Daria-creator-lab requested changes

2024-04-01 08:39 UTC, Daria-creator-lab commented on .github/workflows/setup_pr.yml
Почистить папки 
 
Такого быть не должно 
![image](https://github.com/itsecd/isb/assets/73466150/b4c3e83c-7eec-4a39-a299-de3f430ac210)

2024-04-01 08:39 UTC, Daria-creator-lab commented on lab_2/task2/result_of_tests.txt
> +1.7111556336535152
Значение для 1 теста неверные

2024-04-01 08:39 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +        sum_values = sum(1 if bit == '1' else -1 for bit in bitstring)
проверьте формулу

2024-04-01 08:39 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +    with open(os.path.join("lab_2", "task2", "result_of_tests.txt"), 'w') as sequences:
Никаких захардкоженных путей чисел в коде быть не должно. 
Вынести в файл с настройками

2024-04-01 15:31 UTC, fl1n4 commented on .github/workflows/setup_pr.yml
Извините за вопрос, а как это сделать?

2024-04-01 16:16 UTC, fl1n4 commented on lab_2/task2/NIST_tests.py
> +    with open(os.path.join("lab_2", "task2", "result_of_tests.txt"), 'w') as sequences:
Добавил файл с параметрами (params.json) и получал пути из него для дальнейшего получения последовательностей.

2024-04-08 06:26 UTC, fl1n4 commented on lab_2/task2/NIST_tests.py
> +    with open(os.path.join("lab_2", "task2", "result_of_tests.txt"), 'w') as sequences:
@Daria-creator-lab

2024-04-08 07:47 UTC, Daria-creator-lab requested changes

2024-04-08 07:47 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +        M = block_size
вот это зачем?

2024-04-08 07:47 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +import mpmath
не соответствует PEP

2024-04-08 07:47 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +    path2 = path['path_output']
добавить обработку ошибок здесь и дальше

2024-04-12 08:12 UTC, Daria-creator-lab requested changes

2024-04-12 08:12 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +
количество пустых строк между import и from не соответствует PEP

2024-04-12 08:12 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +        M = 8 #block size
если вам нужен комментарий, чтобы вспомнить что это за переменная, вы можете назвать ее block_size
\+ так ваш код станет читабельнее для других

2024-04-12 08:12 UTC, Daria-creator-lab commented on lab_2/task2/NIST_tests.py
> +        logging.error("Error decoding JSON.")
добавьте информацию об объекте исключения

2024-05-03 06:06 UTC, closed without merging