6213 Козловская К.А. лаб. 1 Вариант-8
itsecd/isb pull request #64
Opened 2024-03-31 16:16 UTC by Pomi44

1. Зашифровать текст (original_text.txt)  использовала шифр Цезаря со сдвигом 3. код решение для первой задачки task_1
2. Дешифровка заданного текста task_2

2024-04-01 09:30 UTC, Daria-creator-lab requested changes

2024-04-01 09:30 UTC, Daria-creator-lab commented on lab_1/task_1/__pycache__/w_r_files.cpython-311.pyc
Почистить файлы 

И верните ключ в директорию, в которой работаете 
![image](https://github.com/itsecd/isb/assets/73466150/1cab1c1f-1534-4949-a06d-5550834b6ee3)

2024-04-01 09:30 UTC, Daria-creator-lab commented on lab_1/task_1/text_crypto.py
> +
не соответствует PEP

2024-04-01 09:30 UTC, Daria-creator-lab commented on lab_1/task_1/text_crypto.py
> +        output_filename: The name of the file to write the key to.
Добавьте в эту функцию возможность расшифровать зашифрованный вами текст. 
Заодно проверите корректность работы вашего алгоритма шифрования.

2024-04-01 09:30 UTC, Daria-creator-lab commented on lab_1/task_1/w_r_files.py
> +
Поправьте везде количество пустых строк между функциями

2024-04-01 13:04 UTC, Pomi44 commented on lab_1/task_1/__pycache__/w_r_files.cpython-311.pyc
я не до конца поняла про почистить файлы, нужно убрать кэш?

2024-04-01 13:09 UTC, Pomi44 commented on lab_1/task_1/text_crypto.py
> +        output_filename: The name of the file to write the key to.
я могу дописать еще одну функцию которая будет расшифровывать, либо переделать функцию encrypt_with_key чтобы она зависела от параметра указанного в config

2024-04-05 05:45 UTC, Daria-creator-lab approved these changes

2024-04-05 06:35 UTC, closed without merging