6211 Фролкин Н.С. Лаб.3 Вар.4
itsecd/isb pull request #65
Opened 2024-03-31 16:43 UTC by nick-vivo

сделал гибридную криптосистему. 3des. все выводы в resource. реализовано ui, хотя для такой простой задачи я считаю это лишним, но это было в тз. код написан на pep, python...

2024-04-01 13:22 UTC, ladyitsecurity requested changes

2024-04-01 13:22 UTC, ladyitsecurity commented on lab_3/main.py
> +import src.hybrid_tripleDES as hybrid
Не соответствует PEP.

2024-04-01 13:22 UTC, ladyitsecurity commented on lab_3/src/encryption_algorithms/asymmetric.py
> +def encrypt(text: bytes, public_key: RSAPublicKey) -> bytes:
Не соответствует PEP.

2024-04-01 13:22 UTC, ladyitsecurity commented on lab_3/src/hybrid_tripleDES.py
> +from .encryption_algorithms.consts import DEFAULT_KEY_BYTES_FOR_TRIPLEDES, DEFAULT_LEN_BYTES_PADDING_BLOCK_FOR_TRIPLEDES
Не соответствует PEP.

2024-04-01 14:16 UTC, nick-vivo commented on lab_3/src/encryption_algorithms/asymmetric.py
> +def encrypt(text: bytes, public_key: RSAPublicKey) -> bytes:
если я правильно понял, придирка в названии одинаковом названии функций для разных ключей. это не требования pep, а рекомендация, а значит это соотвествует pep

2024-04-01 14:35 UTC, nick-vivo commented
> если я правильно понял, придирка в одинаковом названии функций для разных ключей. это не требования pep, а рекомендация, а значит это соотвествует pep

2024-04-05 14:31 UTC, ladyitsecurity commented on lab_3/src/encryption_algorithms/asymmetric.py
> +def encrypt(text: bytes, public_key: RSAPublicKey) -> bytes:
> если я правильно понял, придирка в одинаковом названии функций для разных ключей. это не требования pep, а рекомендация, а значит это соотвествует pep

Нет, _"придирка"_ не в этом.

2024-04-05 14:39 UTC, ladyitsecurity requested changes

2024-04-05 14:39 UTC, ladyitsecurity commented on lab_3/main.py
> +if __name__ == "__main__":
не соответствует PEP.

2024-04-05 14:39 UTC, ladyitsecurity commented on lab_3/src/encryption_algorithms/SymmetricTripleDES.py
> +        return self.__init_vector
Уже говорила об этом на очном занятии. И смотреть код дальше не вижу смысла до исправления.

2024-04-05 14:39 UTC, ladyitsecurity commented on lab_3/src/encryption_algorithms/asymmetric.py
> +def generate_private_key(public_exponent: int = 65537,
не соответствует PEP.

2024-04-05 16:10 UTC, nick-vivo commented on lab_3/src/encryption_algorithms/SymmetricTripleDES.py
> +        return self.__init_vector
а следовало бы. Потому что в названии прописано " stored key " то есть здесь хранится зашифрованный ключ, а не оригинал

2024-04-09 07:55 UTC, ladyitsecurity commented on lab_3/src/encryption_algorithms/SymmetricTripleDES.py
> +        return self.__init_vector
Нет, причина не в этом, подумайте еще... И хранить ключ в классе - большая дыра в безопасности...

2024-05-08 16:00 UTC, ladyitsecurity requested changes
Должна быть возможность возможность:

- сгенерировать ключи по своему пути,
- зашифровать свой собственный текст с указанием путей к своим собственным ключам,
- расшифровать свой собственный текст с указанием путей к своим собственным ключам

Нужна дополнительная декомпозиция кода: разделение на несколько модулей: 

- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

2024-05-19 17:38 UTC, nick-vivo commented
Всё было пофикшено. Теперь мы записываем init_vector( вектор инициализации ) в шифруемый текст. Также пофикшены связанные с ним библиотеки. Плюс команды, которые использовались представлены в рапорте.

2024-05-19 17:39 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
Это было написано в методичке... Меняйте методичку

2024-05-19 17:40 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
Плюсом было принято у других. Требования ко всем должны быть одинаковы. Не моя проблема в том, что автор методички описал такой метод для решения этого безобразия...

2024-05-19 17:43 UTC, nick-vivo commented
По поводу последнего. Возможно вы не смотрели код, весь функционал был реализован и описан (последний реквест), тем более специально для вас в рапорте были написаны команды для ввода в терминал!..

2024-05-19 17:48 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
Вы сами написали код, который надо использовать и я теперь должен исправлять методичку???
Если бы вы ничего не написали и дали разработчику самому представить свою реализацию, то претензия была бы допустимойю, однако вы этого не сделали и соотвественно(это логический вывод) ограничили мои возможности в реализации. Это очевидная мысль

2024-05-19 17:48 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
![Screenshot from 2024-05-18 15-54-22](https://github.com/itsecd/isb/assets/126313574/bac2e8ec-fd81-407e-bbb2-d5e72e0311b6)

2024-05-19 17:48 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
![Uploading Screenshot from 2024-05-18 15-54-22.png…]()

2024-05-19 17:49 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
![Screenshot from 2024-05-18 15-54-22](https://github.com/itsecd/isb/assets/126313574/d340e037-f06e-4f2d-8b27-396fc61e06b8)

2024-05-19 17:49 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
![Screenshot from 2024-05-19 13-46-33](https://github.com/itsecd/isb/assets/126313574/f2c3a988-b678-4b74-ba9b-f809c5d7fc36)

2024-05-19 17:50 UTC, nick-vivo commented on lab_3/main.py
> +            Encrypt data using hybrid encryption key pair.
(Специально, если не очевидною) выше скришнот - код представленный в методичке, плюс у других разработчиков реализация аналогичная(принятые работы), соотвественно этого в моей программе быть не должно

2024-05-19 18:36 UTC, nick-vivo commented
Я конечно заменил конструкцию на match case, но так поступать с разработчиком просто омерзительно. Ставить в методичке одно, потом говорить заменить это на другую конструкцию. Задания и требования сами себе противоречат сплошь и рядом

2024-05-19 19:22 UTC, nick-vivo commented on lab_3/src/hybrid_tripleDES.py
> +from .encryption_algorithms.consts import DEFAULT_KEY_BYTES_FOR_TRIPLEDES, DEFAULT_LEN_BYTES_PADDING_BLOCK_FOR_TRIPLEDES
Исправлено

2024-05-22 17:26 UTC, ladyitsecurity commented
> Я конечно заменил конструкцию на match case, но так поступать с разработчиком просто омерзительно. Ставить в методичке одно, потом говорить заменить это на другую конструкцию. Задания и требования сами себе противоречат сплошь и рядом

Конструкция match case не такая сложная, чтобы выражать столь бурное негодование. К тому же это пример реализации. Но если вы считаете это сложной темой, то можете считать это (специальным, если не очевидно) допзаданием. И я это требую от всех. 

А жизнь несправедлива, заказчики всегда хотят чего-то другого и противоречащего, а _разработчикам_ с этим разбираться.

2024-05-23 16:47 UTC, nick-vivo commented
Конструкция match-case уже используется в данной работе. в файле main.py

2024-05-30 10:52 UTC, ladyitsecurity approved these changes

2024-06-07 06:53 UTC, closed without merging