6213 Забиров Радик Р. Лаб.3 Вар.5
itsecd/isb pull request #66
Opened 2024-04-01 11:27 UTC by ZabirovRadik

Реализовано консольное приложение, которое будет выполняет три указанных ниже сценарии:

1. Генерация ключей гибридной системы
2. Шифрование данных гибридной системой
3. Дешифрование данных гибридной системой

Разобрался в принципе работы RSA и симметричного шифрования.

2024-04-08 08:34 UTC, Daria-creator-lab requested changes

2024-04-08 08:34 UTC, Daria-creator-lab commented on lab_3/generate_keys.py
если это модуль для генерации ключей, зачем здесь шифрование и дешифрования текса? 

Нужно поправить декомпозицию кода.

Предлагаю разделить на модули:
- модуль для работы с симметричной криптографией
- модуль для работы с ассиметричной криптографией
- модуль для вспомогательных операций - сериализации/десериализации ключей/текста
- модуль, импортирующий в себя предыдущие и имплементирующий юзкейсы работы с гибридной системой, описанные в задании

Вы можете выбрать другой вариант декомпозиции кода, но только он не должен нарушать SOLID

2024-04-08 08:34 UTC, Daria-creator-lab commented on lab_3/write_read.py
Сделайте один модуль для сериализации/десериализации данных (ключей и текста)

2024-04-10 08:18 UTC, ZabirovRadik commented on lab_3/main.py
> +    match args.mode:
У меня Argparse выполняет роль смены режима работы, а если пользователь хочет генерировать ключи по своему пути, зашифровать текст своими ключами он может внести изменения в "settings.json". Так нельзя?

2024-04-12 08:14 UTC, Daria-creator-lab commented on lab_3/main.py
> +    match args.mode:
Можно, но тогда дайте пользователю возможность загрузить свой settings.json, в котором будут прописаны его пути

2024-04-25 06:01 UTC, Daria-creator-lab approved these changes

2024-05-17 06:31 UTC, closed without merging