6212 Волков В.С. Лаб.1 Вар.5
itsecd/isb pull request #70
Opened 2024-04-01 17:31 UTC by comandir26

В первом задании лабораторной работы я зашифровал текст, используя метод подстановки, а именно шифр Цезаря с ключом. 
Во втором задании я расшифровал текст, используя метод частотного анализа и нашел ключ шифрования.

2024-04-05 13:09 UTC, ladyitsecurity requested changes

2024-04-05 13:09 UTC, ladyitsecurity commented on lab_1/task_1/encryption.py
> +        substitutions[text_letter.upper()] = letters[count-1].upper()
По-моему, как-то много кода для шифра Цезаря..

2024-04-05 13:09 UTC, ladyitsecurity commented on lab_1/task_2/decryption.py
> +        f.write(result)
Аналогично.

2024-04-05 13:09 UTC, ladyitsecurity commented on lab_1/task_2/frequency.py
> +        text = f.read()
В общем, исправить везде по коду.

2024-04-05 13:09 UTC, ladyitsecurity commented on lab_1/task_2/frequency.py
> +    frequency_analysis(settings['encrypted'], settings['frequency_encrypted'])
А если параметры в файле переименуются? Нет смысла в хранении данных в другом файле, если захардкоженность осталась.

2024-04-05 13:09 UTC, ladyitsecurity commented on lab_1/task_2/decryption.py
> +               settings['decrypted'])
Аналогично.

2024-04-06 22:58 UTC, comandir26 commented
При чтении данных из файлов с параметрами, намеренно использую оператор [], а не get, чтобы ловить исключения, а не проверять на None. Подразумеваю, что если параметры(пути для сохранения и чтения) считаны, то они являются корректными. Также вынес константы в отдельный файл и удалил лишний блок if из функции шифрования.

2024-04-07 12:00 UTC, comandir26 commented
Вынес константу в отдельный файл, функции для работы с файлами тоже с отдельном файле. При получении данных из файлов с параметрами(пути для сохранения и чтения), намеренно использую оператор [], а не get, чтобы ловить исключения KeyError и в случае ошибки прошу проверить имена параметров. Функции для чтения возвращают либо корректные данные, либо None, везде где считываю данные, проверяю на None. Функции для сохранения возвращают результат своей работы в виде булевой переменной, также проверяю на успех. Информирую пользователя только об ошибках, если ошибок нет, значит программа сработала корректно.

2024-04-08 10:19 UTC, ladyitsecurity requested changes

2024-04-08 10:19 UTC, ladyitsecurity commented on lab_1/task_1/encryption.py
> +from constants import letters
не соответствует PEP. Исправить везде.

2024-04-08 10:19 UTC, ladyitsecurity commented on lab_1/task_1/encryption.py
> +    substitutions = {",": ",", ".": ".", "-": "-", "?": "?", "!": "!", " ": " "}
Выносим в константы.

2024-04-10 05:56 UTC, ladyitsecurity requested changes

2024-04-10 05:56 UTC, ladyitsecurity commented on lab_1/task_1/files1.py
> +
Не соответствует PEP.

2024-04-10 05:56 UTC, ladyitsecurity commented on lab_1/task_1/encryption.py
> +from typing import Dict
Не соответствует PEP.

2024-04-10 15:08 UTC, ladyitsecurity approved these changes

2024-04-12 08:23 UTC, closed without merging