6211 Зюзин Е.В. Лаб. 2 Вар. 8
itsecd/isb pull request #72
Opened 2024-04-02 17:41 UTC by derasoft004

В ходе лабораторной работы я сгенерировал псевдослучайные бинарные последовательности с помощью стандартных ГПСЧ языков C++ и Java и проверил сгенерированные последовательности на случайность на основе тестов NIST.

Подробности выполнения и результаты проведенных тестов я предоставил в файле 'report.md'.

2024-04-05 14:19 UTC, ladyitsecurity requested changes

2024-04-05 14:19 UTC, ladyitsecurity commented on lab_2/task_2/functions_assistant.py
> +    return max_len
Во-первых, почему 5? Никаких захардкоженных данных. Во-вторых, как-то много кода и даже функции внутри функций для такой простой задачи (блок даже небольшой)

2024-04-05 14:19 UTC, ladyitsecurity commented on lab_2/task_2/tests.py
> +from functions_assistant import substring_in_sentence
А можно не дублировать и сократить, и PEP это позволяет. Или просто импортнуть весь файл.

2024-04-05 14:19 UTC, ladyitsecurity commented on lab_2/task_2/tests.py
> +    return gammainc(3 / 2, xi / 2)
+строка для конца.

2024-04-06 17:41 UTC, derasoft004 commented on lab_2/task_2/tests.py
> +    return gammainc(3 / 2, xi / 2)
странно, в pycharm строка есть, а в гите нет..

2024-04-06 18:15 UTC, closed without merging