6213 Будюк В.А.  Лаб.2  Вар.4
itsecd/isb pull request #8
Opened 2024-02-20 08:06 UTC by Nibuku

В данной лабораторной работе были написаны два гспч ( файлы с кодом генерации: generator.cpp для с++, RandomBitSequence.java  для Java). 
Так же были написаны необходимые тесты Nist. 
Результаты прохождения тестов и выводы представлены в report.md

2024-02-22 06:48 UTC, alxmcs requested changes
Оставшиеся замечания будут уже от @Daria-creator-lab

2024-02-22 06:48 UTC, alxmcs commented on lab_2/RandomBitSequence.java
Спешу огорчить, что в java есть [javadoc](https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html)

2024-02-22 06:48 UTC, alxmcs commented on lab_2/generator.cpp
C++ был у вас в прошлом году, там тоже есть конвенции по документированию кода

2024-02-22 06:48 UTC, alxmcs commented on lab_2/nist_tests.py
> +            pi[5] = 0.1445
Точно обязательно создавать эту структуру каждый вызов метода?

2024-02-22 10:48 UTC, Daria-creator-lab requested changes

2024-02-22 10:48 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +            return p_value > 0.01
Лучше возвращать p_value, значение параметра является более показательным, чем True False
(Применимо для  постобработки результатов, например, построение графиков)

2024-02-22 10:48 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +            return p_value > 0.01
аналогично

2024-02-22 10:48 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +                counter += int(i)
используйте функцию count()

2024-02-22 10:48 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +        quantity = (self.len // 8) * 8
это точно нужно?

2024-02-25 22:23 UTC, Nibuku commented
Вынесла пи-константы из третьего теста в отдельный словарь. Изменила возвращаемое значение: теперь тесты возвращают p_value, а не его сравнение с 0.01

2024-02-26 04:35 UTC, alxmcs approved these changes

2024-02-26 07:29 UTC, Daria-creator-lab requested changes

2024-02-26 07:29 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +                    if float(i) != float(i + 1):
i в данном случае изменяется от [0, len - 1] 
условие будет выполняться всегда (0 != 1,  1!= 2 и тд)
здесь нужно брать i-ый элемент последовательности

2024-02-26 07:29 UTC, Daria-creator-lab commented on lab_2/report.md
> +  * C++: 011111011010010100000110101100111010011011100011100100001110111011100101101101111110010011101001011000101010100010111101000111100
проверить длину последовательности

2024-02-26 07:29 UTC, Daria-creator-lab commented on lab_2/nist_tests.py
> +            sorted_dict = dict(sorted(unit_counts.items(), key=lambda x: x[1]))
ваш словарь для первой последовательности выглядит так {5: 1, 4: 2, 1: 3, 2: 4, 3: 6}
прочитайте задание еще раз 
![image](https://github.com/itsecd/isb/assets/73466150/cdda89b7-0008-4626-800c-6a940c1449dd)

2024-02-26 07:29 UTC, Daria-creator-lab commented on lab_2/report.md
> +3. Тест на самую длинную последовательность единиц в блоке - 0.6092050161081771
пересчитайте еще раз

2024-03-04 06:14 UTC, Daria-creator-lab approved these changes

2024-04-05 07:37 UTC, closed without merging