6211 Алехин И.И. Лаб.1 Вар.1
itsecd/isb pull request #85
Opened 2024-04-10 10:22 UTC by IvanAlehin

В данной лабораторной работе я изучил простейшие методы шифрования текстовых сообщений путем простых подстановок и перестановок.
В первом задании для кодирования текста был использован шифр цезаря.
Во втором задании для декодирования текста был использован частотный анализ.

2024-04-10 15:20 UTC, ladyitsecurity requested changes

2024-04-10 15:20 UTC, ladyitsecurity commented on lab_1/task1/encrypt.py
> +from constants import ALPHABET, PATHS
Не соответствует PEP.

2024-04-10 15:20 UTC, ladyitsecurity commented on lab_1/task1/encrypt.py
> +    :return:
Параметры нужно описать. Везде.

2024-04-10 15:20 UTC, ladyitsecurity commented on lab_1/task2/constants.py
> +
Не соответствует PEP.

2024-04-10 15:20 UTC, ladyitsecurity commented on lab_1/task2/decrypt.py
> +
Так считаем количество или частоту? Частота подразумевает 2 величины - число положительных исходов и общее число чего-либо. Если считаем частоту, то описание неверное и не хватает еще одной величины.

2024-04-11 14:56 UTC, ladyitsecurity requested changes

2024-04-11 14:56 UTC, ladyitsecurity commented on lab_1/task1/file_work.py
Не заметила в первый раз, но тут два повторяющихся файла с идентичным кодом. Если этот файл нужен для двух задач, нужно не дублировать его, а вынести на уровень выше и импортировать его там, где он нужен.

2024-04-11 15:02 UTC, ladyitsecurity commented
Я еще я не увидела файла с ключами... И функции расчета частоты встречаемости....

2024-04-15 09:09 UTC, IvanAlehin commented
Файл с ключами находится в папке files в обоих task
[key.json](https://github.com/IvanAlehin/isb/blob/lab1-var1/lab_1/task1/files/key.json)
[key.json](https://github.com/IvanAlehin/isb/blob/lab1-var1/lab_1/task2/files/key.json)

2024-04-26 07:05 UTC, closed without merging