6212 Яковлев Р.С. Лаб.1 Вар.7
itsecd/isb pull request #86
Opened 2024-04-10 10:49 UTC by Ryedis

Решение к 1 заданию находится в encoder.py, ко 2 в decoder.py

В папке task_1:
• origin.txt – исходный текст
• encode.txt – зашифрованный текст
• key.json – ключ шифрования

В папке task_2:
• origin.txt – зашифрованный текст
• frequency.json – частотный анализ
• decode.txt – расшифрованный текст
• key.json – ключ шифрования

В папке utils:
• constants.py – рус. алфавит
• frequency.py – скрипт для расчета частотного анализа
• r_wr_funcs.py – функции для чтения и записи

2024-04-10 15:35 UTC, ladyitsecurity requested changes

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/decoder.py
> +
В первой лабе можете оставить, но лучше исправить, потому что это костыль. И в следующих лабах не использовать. Если вылезает ошибка - дело в декомпозиции - нужно импортировать во внешней папке внутренний модуль. (И в целом для понимания лучше, потому что есть один главный файл, а остальные в подпапках. А сейчас ключ с текстом, кодом и параметрами для запуска находятся на одном уровне, хоть и в разных папках (это разделение - хорошо).

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/decoder.py
> +    key = read_json(key_json_file)
Одна функция должна выполнять одну задачу. В кодировании еще хоть как-то натянуть можно, что файл читаем, но json тут точно не к месту. Этой части здесь не место.

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/decoder.py
> +    save_txt(output_file, res)
А тут не может быть исключений?.. Исправить.

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/encoder.py
> +
Та же история.

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/encoder.py
> +    save_json(key_json_file, encoded_dict)
А если запятая будет?

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/utils/r_wr_funcs.py
> +from typing import Dict, Optional
Не соответствует PEP.

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/utils/r_wr_funcs.py
> +        return text
А если файл не найден, то и текста нет, что будем возвращать?

2024-04-10 15:35 UTC, ladyitsecurity commented on lab_1/utils/r_wr_funcs.py
> +        return saved
Аналогично. Исправить везде.

2024-04-10 17:09 UTC, Ryedis commented on lab_1/utils/r_wr_funcs.py
> +        return text
Строчкой выше text = None. Если файл не найден, то возвращаем None. В ф-ии save_txt возвращаем False. Подскажите, если не прав.

2024-04-11 06:08 UTC, ladyitsecurity commented on lab_1/utils/r_wr_funcs.py
> +        return text
Это порождает проблемы потом: что вы будете шифровать и дешифровать?

2024-04-11 06:55 UTC, Ryedis commented on lab_1/utils/r_wr_funcs.py
> +        return text
В моем случае, вроде, создастся пустой файл. Но если мы хотим не совершать лишних действий с пустым файлом, то можно аварийно закрыть выполнение программы с помощью exit() в except

2024-04-11 07:38 UTC, ladyitsecurity commented on lab_1/utils/r_wr_funcs.py
> +        return text
Очень интересна формулировка "вроде".
Что вы будете шифровать в новом пустом файле тогда? Или дешифровать.

2024-04-11 07:59 UTC, Ryedis commented on lab_1/utils/r_wr_funcs.py
> +        return text
Сейчас проверил программу. При правильном пути к пустому txt файлу выполняется обработка данных, находящихся в этом файле, собственно пользователь шифровал пустой файл и получил такой же. При неправильном пути в командную строку отправляется фидбек для пользователя и выполнение программы останавливается. Возможно вы намекаете на то, чтобы я добавил обработчик наличия хоть каких-то данных, при отсутствия которых будет кидаться исключение. Если нет, то я не совсем понимаю, что вы хотели бы видеть.

2024-04-11 15:12 UTC, ladyitsecurity approved these changes

2024-04-12 08:58 UTC, closed without merging