6214 Старцева А.В. Лаб. 2 Вар. 8
itsecd/isb pull request #89
Opened 2024-04-10 22:03 UTC by Annaprogrammer300

В данной лабораторной работе были сгенерированы псевдослучайные бинарные последовательности с помощью стандартных ГПСЧ языков Java и C++. Были реализованы 3 теста линейки NIST и проверены, результаты тестов записаны в отдельный файл
.
Сгенерированные псевдослучайные последовательности (код находится в папке "generators", сами последовательности в "sequence.json"
Выполненные три теста NIST для каждой последовательности (реализация находится в "test.py", результаты тестов "result.txt")
Отчет ("result.md")
Функции для работы с файлами json и txt находится в "works_files.py"
Константы и пути вынесены в отдельные файлы соответственно "constans.py" и "config.json"

2024-04-12 08:33 UTC, Daria-creator-lab requested changes

2024-04-12 08:33 UTC, Daria-creator-lab commented on lab_2/lab2/constants.py
Это не исполняемый модуль. Зачем делать его .py?

2024-04-12 08:33 UTC, Daria-creator-lab commented on lab_2/lab2/works_files.py
> +        print("The file was not found")
добавьте информацию об объекте исключения

2024-04-12 08:33 UTC, Daria-creator-lab commented on lab_2/lab2/works_files.py
> +from enum import Enum
не соответствует PEP

2024-04-12 14:48 UTC, Annaprogrammer300 commented on lab_2/lab2/constants.py
Согласна, просто я подумала и что-то надумала неправильно, хотя они должны записываться в почти в начале модуля, я же правильно поняла?

2024-04-15 16:07 UTC, Daria-creator-lab commented on lab_2/lab2/constants.py
Оба варианта правильные. Если вы хотите вынести константы в отдельный файл, то это должен быть файл с настройками (например, json), но никак не исполняемый .py

2024-04-15 16:07 UTC, Daria-creator-lab approved these changes

2024-04-19 11:00 UTC, closed without merging