6213 Журавлев С.А. Лаб.2 Вар.5
itsecd/isb pull request #9
Opened 2024-02-21 13:42 UTC by fl1n4

2024-02-22 06:36 UTC, alxmcs requested changes
Это была демо-версия ревью
Остальные претензии будут от @Daria-creator-lab

2024-02-22 06:36 UTC, alxmcs commented on lab_1/crypter.py
> +                    encoder_text += chr((ord(char) - ord('А') + shift) % 32 + ord('А'))
Как насчет
```py
base_char = 'a' if char.islower() else 'А'
encoder_text += chr((ord(char) - ord(base_char) + shift) % 32 + ord(base_char))
```

2024-02-22 06:36 UTC, alxmcs commented on lab_1/decrypter.py
> +    replace_letter_in_file(path_to_output, path_to_output, 'Ь', 'Щ', indexes_new_letters)
![image](https://github.com/itsecd/isb/assets/70561974/790a135b-28ec-41ac-8c9a-76c89482905a)

2024-02-22 06:36 UTC, alxmcs commented on lab_1/key1.txt
Это безобразие хранить в гуманном формате сериализации

2024-02-22 06:36 UTC, alxmcs commented on lab_1/key2.txt
Это безобразие тоже

2024-02-22 06:36 UTC, alxmcs commented on lab_1/cod5.txt
А можно данные и код разнести по разным директориям внутри `lab_1`?

2024-03-05 06:43 UTC, alxmcs approved these changes

2024-03-06 08:56 UTC, Daria-creator-lab requested changes

2024-03-06 08:56 UTC, Daria-creator-lab commented on lab_1/part1/crypter.py
> +    json_file_path = 'C:/Users/zhura/Desktop/isb/lab_1/part1/params1.json'
Никаких захардкоженных путей

2024-03-06 08:56 UTC, Daria-creator-lab commented on lab_1/part2/decrypter.py
> +            f"An error occurred while writing to the output file: {e}")
поправить обработку исключений

2024-03-06 08:56 UTC, Daria-creator-lab commented on lab_1/part2/decrypter.py
> +    json_file_path = 'C:/Users/zhura/Desktop/isb/lab_1/part2/params2.json'
Никаких захардкоженных путей

2024-03-06 12:39 UTC, alxmcs commented on lab_1/part2/decrypter.py
> +    json_file_path = 'C:/Users/zhura/Desktop/isb/lab_1/part2/params2.json'
Так это путь к файлу с настройками софта. В целом его можно было бы и оставить, но явно не в абсолютном виде.
Например, можно было бы убрать относительный путь к файлу с настройками в модульные константы

2024-03-07 08:52 UTC, alxmcs requested changes

2024-03-07 08:52 UTC, alxmcs commented on lab_1/part1/crypter.py
> +        key_file = os.path.join(current_directory, params.get('key'))
Отдели инфраструктуру своего приложения от бизнес-логики. В эту функцию должны падать только пути к файлам и ключу. Их парсингом из файла настроек должна заниматься другая функция в другом модуле.

2024-03-07 08:52 UTC, alxmcs commented on lab_1/part2/decrypter.py
> +        key_file_path = os.path.join(current_directory, params.get('key'))
Аналогичная беда

2024-03-07 14:50 UTC, alxmcs requested changes

2024-03-07 14:50 UTC, alxmcs commented on lab_1/part1/crypter.py
>  def encoder(json_file_path: str) -> None:
Еще раз - сюда должен передаваться не один путь к жсону с настройками, а только пути к файлам, которые нужны для выполнения этой функции

2024-03-07 14:50 UTC, alxmcs commented on lab_1/part2/decrypter.py
> +def replace_letters(params):
Аналогично

2024-03-11 09:14 UTC, Daria-creator-lab approved these changes

2024-03-11 11:04 UTC, alxmcs approved these changes

2024-04-05 05:13 UTC, closed without merging