6213 Овсянников А. Н. Лаб.1 Вар.3
itsecd/isb pull request #90
Opened 2024-04-11 08:20 UTC by Prodigysy

Лабораторная работа состоит из двух частей: кодирование текста с помощью шифра цезаря и декодирование.
crypt - кодирование текста
decrypt - декодирование
key_1, key_2 - ключи

2024-04-12 21:03 UTC, Prodigysy commented
@Daria-creator-lab

2024-04-15 15:49 UTC, Daria-creator-lab requested changes

2024-04-15 15:49 UTC, Daria-creator-lab commented on lab_1/part_1/crypt.py
> +
вместо if-ов используйте match/case

2024-04-15 15:49 UTC, Daria-creator-lab commented on lab_1/part_2/decrypt.py
> +
вынесите в отдельный модуль функции работы с файлами

2024-04-15 15:49 UTC, Daria-creator-lab commented on lab_1/part_2/decrypt.py
> +        config_params = json.load(json_file)
здесь тоже нужна обработка исключений как в [lab_1/part_1/crypt.py](https://github.com/itsecd/isb/pull/90/files#diff-63b1623cea796ca3609b2e1c46543f7bedd2d7b1583c7068e95e4a70f7a2eacc)

2024-04-15 15:49 UTC, Daria-creator-lab commented on lab_1/part_1/crypt.py
> +def caesar_cipher_encoder(input_path: str, output_path: str, shift: int, key_path: str) -> None:
Сейчас ваша функция может только зашифровывать сообщение. Добавьте возможность его расшифровать.
Так вы сможете проверить корректность вашего алгоритма.  

*подсказка 
для режима(шифрование/дешифрование) используйте Enum

2024-04-15 15:49 UTC, Daria-creator-lab commented on lab_1/part_2/key_2.json
а где функция для частотного анализа? 
как вы ключ получили? 

Очень похоже, что вы взяли этот файл у другого студента

2024-04-17 07:10 UTC, Daria-creator-lab requested changes

2024-04-17 07:10 UTC, Daria-creator-lab commented on lab_1/part_2/decrypt.py
> +        logging.error(f"An error occurred during frequency analysis: {e}")
Это код 6213 Спиридонова К. С. 
Найдите отличия. 

![image](https://github.com/itsecd/isb/assets/73466150/ce07a811-aaa9-4920-88c8-5303fe65142d)


Переписать самостоятельно!

2024-04-17 07:10 UTC, Daria-creator-lab commented on lab_1/part_2/decrypt.py
> +
И это тоже код  6213 Спиридонова К. С.

![image](https://github.com/itsecd/isb/assets/73466150/a6a13378-a475-4836-bc49-27f99b6b40f7)

2024-04-18 09:42 UTC, Daria-creator-lab requested changes

2024-04-18 09:42 UTC, Daria-creator-lab commented
Вижу, как вы хотите и делаете все, чтобы получить новое задание.
Сегодня ваш день! Вам выдается новое задание 🎉🎉 

Реализовать [шифр Виженера](https://en.wikipedia.org/wiki/Vigen%C3%A8re_cipher), вход в программу каждый раз происходит с новым ключом. 
Зашифровать и расшифровать 100 текстов, ключи сохранять в файл. 

*все исходные тексты и шифротексты упаковать в зип. На гитхаб залить только этот зип файл.
файл с ключами лучше сделать json, он должен содержать 100 ключей

2024-04-25 06:17 UTC, Daria-creator-lab requested changes

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +    all_characters = 'абвгдежзийклмнопрстуфхцчшщъыьэюя0123456789!:;'
алфавит вынести в константу или в файл с настройками

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +            if mode == 'decrypt':
для выбора режима шифрования/дешифрования использовать match/case и структуру Enum

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +    with zipfile.ZipFile("encrypted_texts_and_keys.zip", "w") as zip_file:
никаких захардкоженных путей
вынести в файл с настройками

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +        for i in range(100):
Никаких захардкоженных значений/магических чисел в коде быть не должно.
вынести в параметры функции

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +            if action == 'encrypt':
аналогично, использовать match/case и Enum

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +    file_path = "C:\\Users\\user\\Desktop\\isb-main\\isb\\lab_1\\part_2\\master_i_margarita.txt"
никаких захардкоженных путей

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +    decrypt_keys = [generate_random_key(random.randint(5, 10)) for _ in range(100)]
Никаких захардкоженных значений/магических чисел 
Берите этот параметр из файла с настройками

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +            zip_file.writestr(f"{action}_text_{i+1}.txt", processed_text)
добавить обработку исключений

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +        excerpt = '. '.join(sentences[start_index:start_index + num_sentences]) + '.'
добавить обработку исключений

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +        json.dump(key_dict, file, ensure_ascii=False)
добавить обработку исключений

2024-04-25 06:17 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +from pathlib import Path
не соответствует PEP

2024-04-27 07:28 UTC, Daria-creator-lab requested changes

2024-04-27 07:28 UTC, Daria-creator-lab commented on lab_1/part_1/crypt.py
> +            text = file.read()
Как это у вас работает, если вы сначала что-то делаете с исходным текстом, а только потом его считываете?

2024-04-27 07:28 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +        num_sentences = settings.get('num_sentences', 5)
Зачем вы здесь читаете файл с настройками? Вы его уже прочитали в мейне.
В функцию передавайте только пути до нужных файлов и необходимые параметры

2024-04-27 07:28 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +
Добавить обработку исключений

2024-04-27 07:28 UTC, Daria-creator-lab commented on lab_1/part_2/vigenere_cipher.py
> +
Вы зачем здесь значения параметров прописываете? Вы их должны получить из файла с настройками

2024-04-29 04:50 UTC, Daria-creator-lab approved these changes

2024-05-17 07:32 UTC, closed without merging