6214 Чан Куанг Минь Лаб.3 Вар.4
itsecd/isb pull request #94
Opened 2024-04-12 19:47 UTC by quangminh-202

В лабораторной работе 3, я использую асимметричное кодирование (RSA) и симметричное кодирование (TripleDES). Я использую симметричное шифрование для шифрования текста и асимметричное шифрование для шифрования симметричного ключа шифрования, что также является принципом работы веб-сайтов (https://) для обеспечения безопасности пользователей.
Веб-сайты (http://) не используют шифрование, поэтому информацию легко украсть. это сайт, на который злоумышленники заманивают пользователей.

2024-04-17 10:29 UTC, Daria-creator-lab requested changes

2024-04-17 10:37 UTC, Daria-creator-lab commented
Оберните все в классы

2024-04-17 17:55 UTC, quangminh-202 commented
Я добавил class TripleDES и class RSA, исправил исключения и создал метод, который требовал от пользователей вводить длину ключа и давал возможность повторного ввода.

2024-04-18 08:25 UTC, Daria-creator-lab requested changes

2024-04-18 08:25 UTC, Daria-creator-lab commented on lab_3/RSA_asymmetric.py
Почитайте о классах в питоне https://docs.python.org/3/tutorial/classes.html
В каждом классе обязательно должен присутствовать \_\_init__

2024-04-26 12:11 UTC, quangminh-202 commented
Я добавил метод __init__.

2024-04-27 07:32 UTC, Daria-creator-lab approved these changes

2024-05-22 05:35 UTC, closed without merging