6212 Косенко Михаил Романович Лаб.2 Вар.2
itsecd/isb pull request #96
Opened 2024-04-13 15:29 UTC by KosenkoMichael

Генерация и тестирование с использованием NIST тестов псевдослучайных числовых последовательностей на языках C++ и Java

2024-04-14 14:24 UTC, ladyitsecurity requested changes

2024-04-14 14:24 UTC, ladyitsecurity commented on lab_2/func.py
Такие маленькие куски кода не нужно выносить в отдельные файлы.

2024-04-14 14:24 UTC, ladyitsecurity commented on lab_2/nist.py
> +import mpmath
Не соответствует PEP.

2024-04-14 14:24 UTC, ladyitsecurity commented on lab_2/nist.py
> +        return math.erfc(S/(2**0.5))
reformat code есть кнопочка

2024-04-14 14:24 UTC, ladyitsecurity commented on lab_2/Result.md
А ваш код выдал 0, 276.... и 0,301... Кто врет?  И добавить в этот файл последовательности.

2024-04-14 16:35 UTC, KosenkoMichael commented on lab_2/Result.md
Склонировал, запустил еще раз. Числа получаются ровно такие, какие указаны в 
Result.md

2024-04-15 12:46 UTC, ladyitsecurity commented on lab_2/Result.md
Значит, вы получили некорректный результат и тест работает некорректно)

2024-04-15 12:54 UTC, ladyitsecurity requested changes
Ну и результат на 3 тест непонятно какие числа то получаются в итоге?

2024-04-15 12:54 UTC, ladyitsecurity commented on lab_2/nist.py
> +import mpmath
Не исправлено.

2024-04-15 14:03 UTC, KosenkoMichael commented on lab_2/nist.py
> +import mpmath
Сначала импортированы предустановленные библиотеки, после этого - внешние библиотеки, как и сказано в PEP - соглашении.

2024-04-17 05:31 UTC, ladyitsecurity commented on lab_2/nist.py
> +import mpmath
Все три библиотеки стандартные. А "предустановленными" первые две могут быть, если вы используете то же окружение, что и в первой, например, лабе.

2024-04-17 11:04 UTC, KosenkoMichael commented on lab_2/nist.py
> +import mpmath
Понял, поправил

2024-04-21 15:43 UTC, ladyitsecurity approved these changes

2024-04-26 10:25 UTC, closed without merging